### ISSUE TITLE
asp.net core 3.1 CORS

### ISSUE THREAD

**Issue by CharlesZHENG** [tusdotnet/tusdotnet#101]
the sample AspNetCore_netcoreapp3.1_TestApp does not contains CORS code in Startup.cs,but AspNetCore_netcoreapp2.2_TestApp does, how should i config asp.net core 3.1 application  with tusdotnet to fix CORS?

**Comment by CharlesZHENG** [comment]
I write code like AspNetCore_netcoreapp2.2_TestApp to fix CORS in my asp.net core 3.1 application, it does not work, I think maybe I need some help.thanks.

**Comment by smatsson** [comment]
Hi,

Hard to tell as you haven't provided any details on error messages or similar. I have updated the two test sites for 3.1 and 3.0 to include CORS and it seems to work fine.
