### ISSUE TITLE
Cors issue

### ISSUE THREAD

**Issue by 7amou3** [tusdotnet/tusdotnet#104]
Hello,
I have 2 applications each one is hosted on it's own webserver (Kestrel)
* The first application is the storage server, exposed on port 5123 (I have configured the cors as suggested in the [wiki](https://github.com/tusdotnet/tusdotnet/wiki/Cross-domain-requests-(CORS)))
* The second application is an angular app, exposed on port 4200.

When I run the application a lot of http PATCH requests are made to the server but the file is not uploading [image](https://i.imgur.com/EeD7xgf.png) the console has no error too.
the storage folder has the following [files ](https://i.imgur.com/ZnTogCH.png)

Any idea? 
Thanks

**Comment by keithotto** [comment]
The cors related issues I had showed up in the browsers developer console as errors. The main one I had wasn't really even a CORS error but an unhandled exception being thrown in the OnFileCompleteAsync event handler I setup on tus config object.

**Comment by 7amou3** [comment]
Silly me 🤫 chunksize was set to 0 in the client side
