### ISSUE TITLE
Unable to resume files after deployment

### ISSUE THREAD

**Issue by dhruv-hindocha** [tusdotnet/tusdotnet#105]
Hi @smatsson ,

We are having an ASP .Net core 3.0 application and using the tusdotnet for the resumable file feature. When running locally using IIS or kestrel it works fine. But when we put this behind nginx reverse proxy, the file resume does not work. It always starts from 0. Not sure if there is any header information being missed when using nginx reverse proxy. 

Here is my nginx host configuration
![image](https://user-images.githubusercontent.com/62242386/95363651-5a49f600-08ed-11eb-9074-d7231a097c9a.png)

Here are some snippets from startup file
![image](https://user-images.githubusercontent.com/62242386/95363730-777ec480-08ed-11eb-96c0-013895b7a1ce.png)
![image](https://user-images.githubusercontent.com/62242386/95363834-9b420a80-08ed-11eb-97e3-6063e5d741b5.png)

Here is my TusConfigurationFile

![image](https://user-images.githubusercontent.com/62242386/95363913-b90f6f80-08ed-11eb-8952-1916c99118cf.png)

I have used the configuration that you provided from demo app

Let me know if we can modify anything there.

Thank you!

**Comment by smatsson** [comment]
Hi,

I am no expert in nginx but I would thing that the problem is that nginx by default caches the entire request before passing it upstream. According to the docs you can disable this by setting `proxy_request_buffering` to `off`. 

https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering

**Comment by dhruv-hindocha** [comment]
Hi @smatsson ,

Thank you for a quick response. I tried adding the proxy_request_buffering in my nginx.conf and default.conf file and it worked. 

Here is the updated nginx configuration and nginx host configuration filles.
![image](https://user-images.githubusercontent.com/62242386/95571822-aceaf580-0a46-11eb-8ede-82393da59bd7.png)

![image](https://user-images.githubusercontent.com/62242386/95571880-c2f8b600-0a46-11eb-9af0-0ce23a7ff867.png)
