### ISSUE TITLE
A question about uploading files to an FTP server using FluentFTP

### ISSUE THREAD

**Issue by aspian-io** [tusdotnet/tusdotnet#107]
First of all, thank you for making tusdotnet project to provide dotnet developers with the ability of using Tus. 

I am using tusdotnet in my asp.net core 3.1 project with uppy and react and I have a question about uploading files to an FTP server with FluentFTP.

I can connect to my FTP server through FluentFTP and upload files like this:

```
using FluentFTP;

// creating FTP client
FtpClient client = new FtpClient(_baseUri, _port, _username, _password);
// Connecting to the FTP server
await client.ConnectAsync();

using (var stream = file.OpenReadStream())
{
     ...
     // Uploading file to the FTP server
     var ftpStatus = await client.UploadAsync(stream, fileRelativePath);

   ...

}

 // disconnect!
await client.DisconnectAsync();
```

I have read some articles in wiki of tusdotnet repo about its interfaces. If I should change any implementation please explain which methods need to be changed in new implementation and how could I make tusdotnet to use new implementation instead of its default implementation.

**The question is, how can I use tusdotnet in a way that I can upload files directly to the FTP server using FluentFTP?**

Thank you in advance...

**Comment by smatsson** [comment]
Hi!

What you are looking for is a custom store so start by reading this article: https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store

The interfaces that your store need to implement depends on what extensions from the tus protocol you need as each interface represent an extension.

As a baseline you need to implement [`ITusStore`](https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store#itusstore) to have support for the core protocol and probably also [`ITusCreationStore`](https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store#ituscreationstore) to be able to create new files.

Then pass your own store to the setup of tusdotnet:
```
app.UseTus(httpContext => new DefaultTusConfiguration
{
    Store = new YourCustomStore(), // <-- replace with an instance of your store
    UrlPath = "/files"
});
```

**Comment by jkoplo** [comment]
I'm actually doing something similar - in my case using tus as an upload protocol for embedded controllers on an Edge server and then FTPing received files to a final destination on a different server. I hadn't considered creating an FTP backend for tusdotnet, but I don't think I'd want to. In my scenario it's better to collect files on the edge server if the network is down.

My strategy is this:
1. On receiving a file (OnFileCompleteAsync) I add the fileid to an SQLite database that keeps track of files to be transferred to FTP.
2. I have a background worker service that periodically queries the SQLite database to see if there are any files that need to be transferred.
3. I use FluentFTP to execute a transfer process. In my case this involves uploading, downloading, checking that the files match and then deleting the file from the TusDiskStore and removing it from my SQLite database.

That may or may not suit your needs, but I've had good success with it thus far in dev.

**Comment by aspian-io** [comment]
That's a good idea. Actually I came up with that idea at first but then I managed to customize TusDiskStore File in tusdotnet lib for my purpose - to connect to FTP server using FluentFTP and stuff like that - and now it works fine. Thanks for your solution though.

**Comment by jkoplo** [comment]
@aspian-io any chance you could commit your changes back or throw them in a new repo? I'm gonna try to make mine available as well after some polish.

**Comment by aspian-io** [comment]
@jkoplo Sorry for the late response. I've been so busy lately. Actually I made use of some original implementations of tusdotnet and added FluentFTP connection through its FtpClient class wherever needed. I used default filenames and folder structure of the original tusdonet just consider that TusDiskStore.cs is renamed to CustomTusDiskStore.cs in my implementation. I didn't get to polish it but I will...  just I used it and it works fine. So implementation is pretty straightforward as you compare them with the original implementation. You can have a look at my custom implementation in my project's Infrastructure in the repo through the following link:

https://github.com/aspian-io/aspian/tree/master/Infrastructure/Upload/Tus
