### ISSUE TITLE
Compatibility with tus implementation

### ISSUE THREAD

**Issue by jkoplo** [tusdotnet/tusdotnet#109]
I'm testing a situation with an embedded Linux machine where I'm trying to upload files to a tus endpoint. I'm using [jackhftang/tusc](https://github.com/jackhftang/tusc) as my tus client since it's statically compiled for ARM and I'm essentially running it from a script. It's an implementation of [go-tus](https://github.com/eventials/go-tus). I did all my testing using the included version of [tusd](https://github.com/tus/tusd) and everything went well.

Now I'm looking to replace the tusd implementation with my own dotnet endpoint using tusdotnet an I'm running into compatibility issues.

jackhftang/tusc automatically uploads with a `filename` metadata instead of `name`. It also doesn't include mime-type. I can work around this by providing my own custom header on the command line, so not a big deal. Or I can bypass the checks included in the examples.

The real issue is when I upload, I get the following message:
```
http:///files/32bf51e02e21430199e244342c5487a6
Upload incomplete
Patch http:///files/32bf51e02e21430199e244342c5487a6: http: no Host in request URL
```

All of the expected files seem to make it to disk (`<guid>`, `<guid>.expiration`, etc ), but the actual content does not. It looks like the client is implementing something wrong, but it seems to work fine with the tusd implementation. Thoughts?

**Comment by jkoplo** [comment]
I went through the protocol a little more and I realized that this is probably because I'm running in Debug and the the HEAD call is probably returning a different hostname than `localhost` and therefore not a valid endpoint with the IIS dev server. More investigation needed...

**Comment by jkoplo** [comment]
After more testing, I really think the tus implementation in jackhftang/tusc is somewhat broken. Hitting the server provided in that repo with Postman gives me some strange results that don't really line up with what I'm seeing in the protocol document.

**Comment by smatsson** [comment]
Hi! 

Unfortunately I'm not familiar with that client but I might be able to give you some pointers anyway. :) 

> jackhftang/tusc automatically uploads with a filename metadata instead of name. It also doesn't include mime-type. I can work around this by providing my own custom header on the command line, so not a big deal. Or I can bypass the checks included in the examples.

The examples in the test sites were added just to showcase that one can decline requests that do not conform to domain logic. I should probably remove that part as people seem to think that it is required while in reality the tus protocol does not keep track of any required metadata and leaves it to the client/server contract.

>Patch http:///files/32bf51e02e21430199e244342c5487a6: http: no Host in request URL

This seems like the entire host is missing? It should probably be something like `http://localhost/files/...`. Have you tried using `127.0.0.1` instead of `localhost` as the host to see if that solves the issue? It's strange that it worked with tusd (also on localhost?).

**Comment by jkoplo** [comment]
After lots of testing it's still a bit of a mystery, but I do have some clues. In fact I may have figured it out now that I'm reflecting a bit. I ended up writing most of my own client in the native application instead of shelling out to the executable so this might be a moot point now.

While I was writing the POST/HEAD/PATCH flow I tested against a couple endpoints - both my `tusdotnet` code and the main `tusd` server. There was one thing that I shrugged off and fixed at the time when I was switching between them, but it makes sense now.

I believe that `tusd` returns a location like:
```
Location: https://tus.example.org/files/24e533e02ec3bc40c387f1a0e460e216
```
and I think `tusdotnet` returns location like:
```
Location: /files/24e533e02ec3bc40c387f1a0e460e216
```

I'm not sure which is proper, but the examples on [tus.io](tus.io) show the full path with hostname included.

Could that be it?

**Comment by jkoplo** [comment]
I can confirm that the issue is that `tusd` returns an absolute path and `tusdotnet` returns a relative path. According to the documentation for the tus protocol either one is acceptable:

> The Server MUST acknowledge a successful upload creation with the 201 Created status. The Server MUST set the Location header to the URL of the created resource. This URL MAY be absolute or relative.

So the bug lies in either the client binary or the client library - either way, not a concern for this project! 

Thanks again for the library. I appreciate it.

**Comment by smatsson** [comment]
Interesting issue and good find in your investigation. I might add "full urls" as a setting in an upcoming release. For now you can work around this issue by adding an extra middleware:

```
app.Use(async (httpContext, next) =>
{
    await next();

    var isPostRequest = httpContext.Request.Method.Equals("POST", StringComparison.InvariantCultureIgnoreCase);
    var isCreatedStatusCode = httpContext.Response.StatusCode == 201;

    if (isPostRequest && isCreatedStatusCode && httpContext.Response.Headers.TryGetValue("Location", out var locationHeader))
    {
        httpContext.Response.Headers["Location"] = httpContext.Request.Scheme + "://" + httpContext.Request.Host + locationHeader;
    }
});

app.UseTus(...);
```

**Comment by jkoplo** [comment]
"Full URLs" as a setting is another good option. I'm slammed currently, but that seems small in scope and a good excuse to contribute to this project.

Mind if I take a run at it and send a PR in the next month or two?

**Comment by smatsson** [comment]
Please do 👍
