### ISSUE TITLE
ITusReadableStore should probably implement GetUploadMetadataAsync

### ISSUE THREAD

**Issue by jkoplo** [tusdotnet/tusdotnet#112]
Once I have a file transfer completed I'd like to do some processing on the file. I can get the file data itself via `ITusReadableStore` but I also need some of the metadata to do my processing. It _seems_ like metadata should also be available from the readable store.

This isn't a big deal right now - I pass the TusDiskStore to the class that needs it, but I'd rather depend on the ITusReadable instead.

**Comment by smatsson** [comment]
`GetMetadataAsync` is implemented by `ITusFile` so it already does :) 

```
var readableStore = (ITusReadableStore)store;
ITusFile file = await readableStore.GetFileAsync("myId", CancellationToken.None);
Dictionary<string, Metadata> metadata = await file.GetMetadataAsync(CancellationToken.None);
```

**Comment by jkoplo** [comment]
Man, I'm spread too thin and didn't remember my actual implementation when I skimmed through my top level DI.

I actually am getting the metadata off the ITusFile - it was deleting the files after I transferred them off that I needed the TusDiskStore. Since I'm reading and deleting files as part of my FTP archiving I either need both ITusReadableStore and ITusTerminationStore or just the actual class. I suppose I could create a new interface locally that just inherits off those two.

Anyway, I'll close this.  Just the ramblings of someone on a deadline...

**Comment by smatsson** [comment]
Haha no worries. The "needing multiple interfaces" part is one of the things I feel didn't turn out great about tusdotnet, but now I need to keep backwards compatibility so can't really change it at this point. Maybe in a future breaking changes version, who knows?
