### ISSUE TITLE
[New Feature]support slice the file while is uploading a huge file

### ISSUE THREAD

**Issue by serfend** [tusdotnet/tusdotnet#114]
as user request for upload , i could return a `guid` for the uploading transaction which record user file meta.
then user request upload for the body of file with every slice of id.
finally , even though user exit accidently, it can be restore when user connect again.

**Comment by smatsson** [comment]
Hi,

I'm sorry but I'm having a hard time understanding this feature. It sounds like a combination of [chunk size](https://github.com/tus/tus-js-client/blob/master/docs/api.md#chunksize) and using the [concatenation extension](https://tus.io/protocols/resumable-upload.html#concatenation)? 

Could you explain the feature in more detail please?

**Comment by serfend** [comment]
thanks for your reply,
i think it would act like somehow netdisk handle with suddently shutdown.
![image](https://user-images.githubusercontent.com/20139227/100335532-0ff11580-3010-11eb-908c-fd12f070729e.png)

**Comment by serfend** [comment]
thanks for your reply,
i think it would act like somehow netdisk handle with suddently shutdown.
![image](https://user-images.githubusercontent.com/20139227/100335675-3a42d300-3010-11eb-9609-a16891197b9f.png)

**Comment by smatsson** [comment]
Hi again,

I'm sorry but I still don't understand how this differs from how the tus protocol already works? The client will upload a file and if the connection dies then the client can ask the server for how much of the file is already transferred and continue to upload where the connection was cut of.

Here is a screenshot from https://tus.io/demo.html where I'm just running the normal flow:
![image](https://user-images.githubusercontent.com/4600361/101145873-a62dc880-361a-11eb-8c14-397742f05d97.png)

**Comment by serfend** [comment]
i'm sorry,i see

**Comment by smatsson** [comment]
No worries. 😊 Feel free to open an issue for any other questions you might have.
