### ISSUE TITLE
OnFileCompleteAsync never gets fired when uploading a file with size 0.

### ISSUE THREAD

**Issue by oquirion** [tusdotnet/tusdotnet#119]
Using version 2.2.1 of tusdotnet.
Step to reproduce:

1. Create new text file name 'empty.txt' without writing anything to it.
2. Try to upload the file.

If you need more specification, just poke me.
I've haven't seen the bug reported, nor corrected in the last 2 release.
I'm waiting for you call on it.

Best regards,
Oliver

**Comment by smatsson** [comment]
Haha I love this bug. :D What was your use case when you found this?

**Comment by oquirion** [comment]
Actually, I've found out the bug out of pure luck. We're using tus library to perform file upload and as I was manually testing it, I accidently tried to send a brand new txt file that was lying around on my desktop and it failed. I've quickly created a bug issue on Jira before forgetting about it (because it's such an edge case). So here I am, a few weeks from then, I've just debugged it down to tus library. I was looking on github to see if it has been reported/fix in the latest release and if the whole project was still alive. I'm glad someone pick up the phone!! Do you need anything to help you reproduce it?
Regards,

**Comment by smatsson** [comment]
I think I'm good right now to reproduce it and will look into it as soon as I get the time. Thanks for reporting!

**Comment by oquirion** [comment]
Thank you very. I'll update the lib and test it in our env.
Regards'
Oli
