### ISSUE TITLE
How to change file name when use TusDiskStore

### ISSUE THREAD

**Issue by zhaokuohaha** [tusdotnet/tusdotnet#122]
Hi ,
    as the title, I don't known how to save files use custom file name when I use the TusDiskStore as my store provider.  
    it seems that hard code to use file id: https://github.com/tusdotnet/tusdotnet/blob/096db753d4af2875179e76f61d4d6ae2e2cc94c8/Source/tusdotnet/Stores/TusDiskStore.cs#L198-L208

**Comment by zhaokuohaha** [comment]
another problem ,  I can't use  [Custom-File-Id-Provider](https://github.com/tusdotnet/tusdotnet/wiki/Custom-File-Id-Provider) 
the release version can not fine ITusFileIdProvider :

**Comment by smatsson** [comment]
Hi,

Custom file IDs are not yet released to nuget so you will either have to to wait for it or build your own package from source.

**Comment by zhaokuohaha** [comment]
> Hi,
> 
> Custom file IDs are not yet released to nuget so you will either have to to wait for it or build your own package from source.

Oh I see , thanks
