### ISSUE TITLE
Access TusStore from Controller

### ISSUE THREAD

**Issue by Mobiusimmortal301** [tusdotnet/tusdotnet#125]
I've been attempting to access the TusStore in a controller to finish any processing of my files. 

I know the OnFileCompleteAsync event exists, but I'm not a fan of having to use a service scope here in order to have access to my database when I finish processing my file. 

Ideally, I want to access my TusStore in a separate controller to handle the additional processing of my files on the server side. 

Unfortunately, I can't find any examples or hints in the wiki here or other places online, so I hope you can provide me with some in-site.

**Comment by smatsson** [comment]
Hi,

I don't really follow your argument about the service scope but anyway you need to register the store used in your IOC and then inject it into the controller. The store is split amongst multiple interfaces used internally as feature detection so something like this:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddCors();
    services.AddSingleton(CreateTusConfiguration);
    services.AddHostedService<ExpiredFilesCleanupService>();

    services.AddAuthentication("BasicAuthentication")
            .AddScheme<AuthenticationSchemeOptions, BasicAuthenticationHandler>("BasicAuthentication", null);

    // The same store used in your configuration when calling app.UseTus.
    var store = new TusDiskStore(@"C:\tusfiles\");
    services.AddSingleton<ITusReadableStore>(store);
}
```

You might also want to inject ITusStore directly to check that the file is completed:
```csharp
services.AddSingleton<ITusStore>(store);
```

This will be a bit easier once the relevant parts of #116 has been implemented.

**Comment by Mobiusimmortal301** [comment]
@smatsson, thank you for the quick response. That is exactly what I needed.

As for the service scope I mentioned, I had to do this inside the OnFileCompleteAsync due to IoC:

`using (var serviceScope = app.ApplicationServices.CreateScope()) 
{
      serviceScope.ServiceProvider.GetRequiredService<CmsDbContext>();

      serviceScope.ServiceProvider.GetRequiredService<IVideoManager>();

      var fms = serviceScope.ServiceProvider.GetRequiredService<IFileManagementService>();

      var file = await eventContext.GetFileAsync();

      await fms.HandleFileUploadFinished(file, httpContext.RequestAborted);
  }`
