### ISSUE TITLE
Change urlpath

### ISSUE THREAD

**Issue by sajad39khalili** [tusdotnet/tusdotnet#129]
How can i change urlpath dynamic and i use multi controllers and actions

**Comment by smatsson** [comment]
Hi! 

It's described in short here: https://github.com/tusdotnet/tusdotnet/wiki/Configure-tusdotnet

You can return different configs based on the incoming http context, e.g.:

```
app.UseTus(httpContext => 
{
    if(SomeCondition(httpContext))
    {
        return new DefaultTusConfiguration
        {
            UrlPath = "/somefiles";
        }
    }

    return new DefaultTusConfiguration
        {
            UrlPath = "/someotherfilesfiles";
        }
});
```

**Comment by sajad39khalili** [comment]
Thanks .how can i use in multi action and do some different thing before and after .example authorize . Save database . Log .check sizefile and file extension .all things may be different in every actions

**Comment by smatsson** [comment]
Lots of questions there. You should read up on the wiki on how to configure events: https://github.com/tusdotnet/tusdotnet/wiki
