### ISSUE TITLE
HttpError 409 on Patch Method

### ISSUE THREAD

**Issue by danielJunio0** [tusdotnet/tusdotnet#131]
Hello.
I'm trying to upload a video to azure blob storage, i implement my own service to upload and set de service on Store of the tusCofiguration.
On client side i set chunkSize to 1000000. All Video is uploaded on my blob storage, but a problem happens.
When i start a upload, some requests of Patch Method responses with status code 409 and with a message like this "Offset does not match file. File offset: 9523200. Request offset: 18995200". I tryied everything to resolve this issue but i think the problem is from server side.  Can you guys helpe me with this?

**Comment by smatsson** [comment]
Hi,

The error indicates that the Upload-Offset provided by the client does not match the current offset of the file. I.e. the server has saved X bytes but the client wants to continue the upload from byte Y. Most likely this is an issue with what offsets your store returns.

The flow is basically this:
1. Client starts the upload by creating the file and will then send a PATCH with Upload-Offset: 0.
2. The server will save the data and return the new offset to the client.
3. The client will upload the next chunk starting at the offset returned from the server.

In terms of method calls for the store, these calls should be made (each step is a new request):
1. CreateFileAsync returning a file id to write data to.
2. AppendDataAsync(fileId from step 1, request stream, cancellation token) returning the number of bytes written this request. The return value here will be used together with the Upload-Offset provided by the client to return the new Upload-Offset.
3. GetUploadOffsetAsync will be called to get the offset of the file and this value will be compared with the Upload-Offset provided by the client.

Without looking at your code my first guess is that one of these methods return an invalid value.

**Comment by danielJunio0** [comment]
Hi

really the error was in the return of one of the methods, the AppendDataAsync was returning from lenght of file, instead of bytes writen.

Thanks for help me.
