### ISSUE TITLE
OnFileCompleteAsync never gets fired when uploading a file with size 0

### ISSUE THREAD

**Issue by VitaliyVrealSoft** [tusdotnet/tusdotnet#134]
I use tusdotnet version 3.0, and when i try to upload empty files, this uploading skip step with onFileCompleteAsync.
Step to reproduce:
1. Create empty txt file and upload it.
2. Nothing detected  in OnFileCompleteAsync. 
With best regards, Vitaliy

**Comment by smatsson** [comment]
Known issue that will be fixed in the next version: https://github.com/tusdotnet/tusdotnet/issues/119

**Comment by heebj** [comment]
@smatsson do you already know when the next version with this fix will be released? I experience an error when using uppy to upload a file on Android from a Google Drive and it might have the same cause:
https://github.com/transloadit/uppy/issues/2860

Thanks!

**Comment by smatsson** [comment]
Hi @heebj 

There are some other features that are in progress that I want to include in the new version so it will probably be a week or so before the new version hits nuget.

**Comment by smatsson** [comment]
https://www.nuget.org/packages/tusdotnet/2.4.0
