### ISSUE TITLE
Using tusdotnet on Azure webapp

### ISSUE THREAD

**Issue by mkgn** [tusdotnet/tusdotnet#141]
Hi,

Since there is no support for Azure storage, I am planning to get the file uploaded to local storage space in Azure Web App and then move it to Azure file shares. I am wondering how this will work in a scaled environment. For example Azure web apps can automatically scale and balance the load between instances if needed. How will this effect any on going uploads?

The above will be a rare case for me since I am not planning to upload gigabytes of data, but would like to know potential pit falls.

**Comment by smatsson** [comment]
Hi,

It should be all right as long as you use sticky sessions for your app service and make sure the clients include the session cookie.
