### ISSUE TITLE
how to get the custom filename in the onSuccess or onAfterResponse function Receive processing

### ISSUE THREAD

**Issue by apchenjun** [tusdotnet/tusdotnet#142]
How to get the custom filename returned by the backend in the onSuccess or onAfterResponse function
![image](https://user-images.githubusercontent.com/4964551/124588849-db89e580-de8b-11eb-9257-93d39e667145.png)

**Comment by tukao89** [comment]
You can create custom response header, some thing like this:

 `eventContext.HttpContext.Response.Headers.Add("X-File-Info", filename);`

**Comment by smatsson** [comment]
Exactly what @tukao89 wrote above. Writing of data returns `204 No Content` to the client so no body can be transmitted.

**Comment by apchenjun** [comment]
@tukao89  @smatsson 
how to get X-File-Info value in client
