### ISSUE TITLE
Add support for endpoint routing

### ISSUE THREAD

**Issue by smatsson** [tusdotnet/tusdotnet#147]
This issue has been split from #116 

**Delimitations**

Initial version will only support the "old" way of doing things, without the controller pattern, e.g.
```csharp
endpoints.MapTus("/files", httpContext => new DefaultTusConfiguration());
```

Dependency injection in other parts of the app will not be included in this issue, i.e. `services.AddTus()` will not be added in this round.

**Comment by AnitaBakhtiari** [comment]
**Hi,
i saw the controller pattern and use it , but unfortunately it is not in latest version and belong to another branch, and i can't take advantage of that on nuget package  , could you merge it ?**

**Comment by smatsson** [comment]
@AnitaBakhtiari I think there is some confusion here. This issue will not add support for the controller pattern. It will however add support for endpoint routing. Is that what you are asking about? The dev branch is not done nor tested and thus will not be merged until completed. If you need it earlier than that, grab the source and compile it yourself. If you find any bugs, feel free to send a PR.

**Comment by AnitaBakhtiari** [comment]
> 

I see , Thank you so much for your response.
and I hope it will be merged as soon as possible.
