### ISSUE TITLE
Store can't find expired files

### ISSUE THREAD

**Issue by Mobiusimmortal301** [tusdotnet/tusdotnet#158]
I followed the implementation for removing expired files found here: 

https://github.com/tusdotnet/tusdotnet/wiki/Removing-expired-incomplete-files

But my TusDiskStore doesn't find any expired files, even though I have a few.

Looking into TusDiskStore.cs file I see that logic is looking for Expired and Incomplete files, but shouldn't this be an or statement instead?

**Comment by smatsson** [comment]
Hi! 

The title of the wiki page basically says why, it's only for removing incomplete expired files. The text doesn't mention it though so it should really be updated. 

Files that are completed are outside the scope of the tus protocol and expiration is only used to indicate for the client when the file upload can no longer be resumed (see example here: https://tus.io/protocols/resumable-upload.html#expiration). Generally one would use `RemoveExpiredFilesAsync` to clean up old incomplete files, while using post processing (e.g. from `OnFileCompleteAsync`) to delete the completed file if not needed anymore. 

Changing this behavior now would be a huge breaking change for all existing implementations so I recommend that you copy the code from [here](https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Stores/TusDiskStore.cs#L319) and modify it to not exclude completed files.

**Comment by Mobiusimmortal301** [comment]
Thank you for the reply. 

Due to my workflow, cleaning up the file during `OnFileCompleteAsync` isn't an option.

The inconsistency of the method name and wiki title led to some confusion, but I understand making changes to a widely used code base isn't feasible.

I did end up copying the code and just removing the incomplete check.

**Comment by smatsson** [comment]
I totally get that. I have re-opened the issue and added a docs tag to it so that the docs can be made clearer. Thanks for reporting and sorry for the inconvenience.

**Comment by smatsson** [comment]
I've updated the wiki. Hopefully it is clearer now: https://github.com/tusdotnet/tusdotnet/wiki/Removing-expired-incomplete-files
