### ISSUE TITLE
Have you tried to use a normal controller?

### ISSUE THREAD

**Issue by SebastianStehle** [tusdotnet/tusdotnet#165]
Hi,
thank you for building this library. I have an existing controller that I would like to improve: https://github.com/Squidex/squidex/blob/master/backend/src/Squidex/Areas/Api/Controllers/Assets/AssetsController.cs#L212

Have you tried to connect the middleware with a controller somehow? I have 5-6 filters that I would have to rebuild otherwise.

**Comment by SebastianStehle** [comment]
Okay, I got it working. 

It is a little bit tricky and perhaps ugly but for me the better alternative to writing dozens of filters again.

I have written the following runner

```
public sealed class AssetTusRunner
{
	private readonly TusCoreMiddleware middleware;

	public AssetTusRunner(ITusStore tusStore)
	{
		var events = new Events
		{
			OnFileCompleteAsync = async eventContext =>
			{
				var file = await eventContext.GetFileAsync();

				eventContext.HttpContext.Items["TUS_FILE"] = file;
			}
		};

		middleware = new TusCoreMiddleware(_ => Task.CompletedTask, ctx => Task.FromResult(new DefaultTusConfiguration
		{
			Store = tusStore,
			Events = events,
			UrlPath = ctx.Items["TUS_BASEURL"]!.ToString()
		}));
	}

	public async Task<ITusFile> InvokeAsync(HttpContext httpContext, string baseUrl)
	{
		httpContext.Items["TUS_BASEURL"] = baseUrl;

		await middleware.Invoke(httpContext);

		return httpContext.Items["TUS_FILE"] as ITusFile;
	}
}
```

Then you can invoke it in your controller:

```
[Route("files/controller/{**catchAll}")]
public async Task<IActionResult> Tus()
{
	// Calculate the URL of the action without the catchAll to forward the middleware the correct base URL.
	var file = await runner.InvokeAsync(HttpContext, Url.Action(null, new { catchAll = (string?)null }));
        
	if (file != null)
	{
		await using var fileStream = await file.GetContentAsync();

		var name = file.FileName;

		if (string.IsNullOrWhiteSpace(name))
		{
			name = Guid.NewGuid().ToString();
		}
        
		Directory.CreateDirectory("uploads");
        
		await using (var stream = new FileStream($"uploads/{name}", FileMode.Create))
		{
			await fileStream.CopyToAsync(stream, HttpContext.RequestAborted);
		}
        
		return Ok(new { json = "Test" });
	}
        
    // Return an empty action result to not set the status code twice. Perhaps null could work as well. 
	return new NoopActionResult();
}

public sealed class NoopActionResult : IActionResult
{
	public Task ExecuteResultAsync(ActionContext context)
	{
		return Task.CompletedTask;
	}
}
```

**Comment by smatsson** [comment]
This is a really creative and cool implementation! Is it the "usual" kind of filters (auth, logging etc) that are used or is it something special? I think you can make this even more MVCish by overriding the HttpResponse in the HttpContext provided for TusCoreMiddleware to get the status code and possible error message. This way you could return the response directly from your controller. Not sure if worth it though :) 

Side note: You can probably check if the stream returned from `GetContentAsync` is a FileStream and then just move the file instead of doing a full copy.

**Comment by SebastianStehle** [comment]
> This is a really creative and cool implementation! Is it the "usual" kind of filters (auth, logging etc) that are used or is it something special?

Both, around 4-5 filters in total.

> I think you can make this even more MVCish by overriding the HttpResponse in the HttpContext provided for TusCoreMiddleware to get the status code and possible error message. 

It is not possible, because after the middleware has set headers you cannot modify the status code anymore or something like this. Therefore I had to return the `EmptyResult`

**Comment by smatsson** [comment]
If you look at how responses are handled in tusdotnet you can see that if you replace the underlying HttpResponse on the HttpContext passed to tusdotnet you can just get the status without sending it to the client. :) The `ResponseAdapter` is what is used throughout tusdotnet when sending responses to the client https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/ExternalMiddleware/Core/TusCoreMiddleware.cs#L93

**Comment by SebastianStehle** [comment]
I see what you mean. This would work as well, I will test this approach. Then I can just write a TusResult class :)

**Comment by SebastianStehle** [comment]
Your approach works, thx. Had to replace the whole context, but it works: https://github.com/Squidex/assets/blob/tus-adapter/Squidex.Assets.TusAdapter/AssetTusRunner.cs

**Comment by smatsson** [comment]
Nice 👍 I'm wondering if this is a common use case that should be supported out of the box? 🤔 It would also give the possibility to run the code outside the middleware, e.g. in services or similar.
