### ISSUE TITLE
Easy way to test several scenarios for custom store

### ISSUE THREAD

**Issue by SebastianStehle** [tusdotnet/tusdotnet#166]
Hi,

I have made a custom store implementation and would like to test it.

So far I am using Tus-js-client and I just have uploaded a simple script to my test server: https://github.com/Squidex/assets/blob/tus-adapter/TusTestServer/wwwroot/upload.html

But I would like to test more cases, e.g. checksums are not implemented with this store.

Do you have any good tips how to test it? e.g. which client do you use or can I reuse some parts of your tests or can they be made reusable?

**Comment by smatsson** [comment]
tusdotnet already has pretty good test coverage that the correct methods are ran for each use case (e.g. when using checksums) so as long as your store implements the correct interfaces this should all work. I would probably focus on testing your store's implementation and for that you can use the TusDiskStore tests as reference (https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet.test/Tests/TusDiskStoreTests.cs)

**Comment by SebastianStehle** [comment]
I have just written a few integration tests. Works good enough.
