### ISSUE TITLE
BUG?: PATCH needs an existing file.

### ISSUE THREAD

**Issue by SebastianStehle** [tusdotnet/tusdotnet#167]
Hi,

if I understand it properly the very basic flow of a Upload is as followed:

1. CLIENT sends HEAD request to ULR (e.g. `/files/<FILE_ID>`). SERVER responds with a 404 to indicate that the content does not exist.
2. CLIENT sends PATCH request to URL (e.g. `/files/<FILE_ID>`) with the full content of the file to upload.

I try to implement a client testing this very basic scenario and it does not work. I have added the source code to my server project to debug through and I found this line of code, which confused me:

https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/IntentHandlers/WriteFileHandler.cs#L197

This basically means that for the PATCH request the file must exist. It works well with the creation extension, but I thought that extensions are fully optional.

**Comment by smatsson** [comment]
Hi,

Yes this is per the spec. `creation` is an optional feature of the protocol. You are free to create the resource to upload to with any type of request you wish if you do not wish to support `creation`. E.g. Vimeo is using a custom http request to create the upload resource and then uses tus for the actual file transfer.

**Comment by SebastianStehle** [comment]
Okay, thank you very much. I though that the Patch is like an implicit Create.

**Comment by smatsson** [comment]
Unfortunately no. It will be in [tus2](https://github.com/tus/tus-v2) :)

**Comment by SebastianStehle** [comment]
Perfect. It works good with Create anyway. So I am fine with that.
