### ISSUE TITLE
ITusReadableStore GetFileAsync Can Support Extension?

### ISSUE THREAD

**Issue by snowchenlei** [tusdotnet/tusdotnet#169]

**Comment by smatsson** [comment]
I have no idea what you are asking. Can you explain in more detail?

**Comment by snowchenlei** [comment]
https://github.com/tusdotnet/tusdotnet/blob/614d908c8870e259171cf08be8ca063681d43842/Source/TestSites/AspNetCore_net6.0_TestApp/Endpoints/DownloadFileEndpoint.cs#L19
This method requires the fileId parameter. But the file name when saving is modified, this method will return null.
Can add `extensionName` Optional parameter?

**Comment by smatsson** [comment]
> But the file name when saving is modified,

What do you mean? Did you change the file id in the `OnFileComplete` callback? If so you will need to grab the file with the new name from disk (or however your store saves data)

> Can add extensionName Optional parameter?

No as tusdotnet accepts any type of resumable uploads that can be any type of data and not just files. "extension" is just a file concept that does not apply here.

**Comment by snowchenlei** [comment]
ok，thanks!
