### ISSUE TITLE
tus and yarp gateway

### ISSUE THREAD

**Issue by junshangshui** [tusdotnet/tusdotnet#170]
My tus setting  
```csharp  UrlPath = "/s1/files"```
My yarp setting
```csharp
"ReverseProxy": {
          "Routes": {
            "serv1": {
              "ClusterId": "cluster1",
              "Match": {
                "Path": "/s1/{**any}"
              },
              "Transforms": [
                { "PathRemovePrefix": "/s1" }
              ]
            },
        }
      }```
My Html tus options must be 
endpoint='http://localhost:802/s1/s1/files' 

sorry my english is not good.

**Comment by smatsson** [comment]
Hi! 

Sorry but I have never used YARP. I would guess that the extra "/s1/" in the tus configuration is what does it. Normally a reverse proxy just forwards the address after whatever prefix you specified to the upstream. For example:

Yarp      ->    tusdotnet
/s1/files      ->    /files

**Comment by junshangshui** [comment]
in my yarp gateway, 
 I wrote the following code and can upload it normally
app.UseEndpoints(endpoints =>
            {
                endpoints.MapReverseProxy(configureApp =>
                {
                    configureApp.Use((context, next) =>
                    {
                        var requestPath = context.Request.Path;
                        if (requestPath.HasValue && requestPath.Value.StartsWith("/s1/files/"))
                        {
                            context.Request.Path = ("/s1" + requestPath);
                        }
                        return next(context);
                    });
                });
            });

**Comment by junshangshui** [comment]
in my yarp gateway,
I wrote the following code and can upload it normally
`app.UseEndpoints(endpoints =>
            {
                endpoints.MapReverseProxy(configureApp =>
                {
                    configureApp.Use((context, next) =>
                    {
                        var requestPath = context.Request.Path;
                        if (requestPath.HasValue && requestPath.Value.StartsWith("/s1/files/"))
                        {
                            context.Request.Path = ("/s1" + requestPath);
                        }
                        return next(context);
                    });
                });
            });`

**Comment by junshangshui** [comment]
in my yarp gateway,
I wrote the following code and can upload it normally
```csharp app.UseEndpoints(endpoints =>
            {
                endpoints.MapReverseProxy(configureApp =>
                {
                    configureApp.Use((context, next) =>
                    {
                        var requestPath = context.Request.Path;
                        if (requestPath.HasValue && requestPath.Value.StartsWith("/s1/files/"))
                        {
                            context.Request.Path = ("/s1" + requestPath);
                        }
                        return next(context);
                    });
                });
            });```

**Comment by smatsson** [comment]
Glad it was solved!
