### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by chrpai** [tusdotnet/tusdotnet#174]
(I problably mean Authorization not Authentication )

I've implemented Tus in a project and it works.  But I'm not sure how to do authentication.  Is this built into the protocol or am I supposed to just to my own custom thing the the metadata  headers? If so, is there somewhere to do it prior to OnFileCompleteAsync?

I've also read issues on MVC, Minimal API and TUS2.  I'm currently using MVC with JWT ClaimRequirement authorization for my end points.    However I am flexible depending on the direction this project is taking.

**Comment by chrpai** [comment]
I see how I can do this:

                OnAuthorizeAsync = async authorizeContext =>
                    {
                        authorizeContext.FailRequest(HttpStatusCode.Unauthorized);
                    }

**Comment by smatsson** [comment]
Oh and I forgot to mention. There is ongoing work to integrate tusdotnet with endpoint routing in ASP.NET Core 3.1 and later which will make this easier as it will just integrate with the existing authorization pipeline. https://github.com/tusdotnet/tusdotnet/tree/dev/147-endpoint-routing

You can then add authorization as with any endpoint:
```
app.UseEndpoints(endpoints =>
            {
                endpoints.MapTus("/files", new DefaultTusConfigur...).RequireAuthorization();
```
