### ISSUE TITLE
Upload-Offset always returns zero

### ISSUE THREAD

**Issue by herberteSantos** [tusdotnet/tusdotnet#176]
I can't restart the upload because the Upload-Offset always returns zero

`        app.UseTus(httpContext => new DefaultTusConfiguration
        {

            // This method is called on each request so different configurations can be returned per user, domain, path etc.
            // Return null to disable tusdotnet for the current request.

            // c:\tusfiles is where to store files
            Store = new TusDiskStore($"{Environment.CurrentDirectory}\\uploads\\store"),
            // On what url should we listen for uploads?
            UrlPath = "/upload",

            MetadataParsingStrategy = MetadataParsingStrategy.AllowEmptyValues,

            Expiration = new AbsoluteExpiration(TimeSpan.FromMinutes(5)), ...`

**Comment by smatsson** [comment]
Hi,

Sounds like an issue with the request never hitting your backend. Did you check the docs on how to configure the reverse proxy?

Nginx: https://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_request_buffering

Kestrel: https://github.com/tusdotnet/tusdotnet/wiki/Configure-Kestrel

IIS: https://github.com/tusdotnet/tusdotnet/wiki/Configure-IIS

**Comment by herberteSantos** [comment]
Resolved!
