### ISSUE TITLE
How to use in k8s (multiple instance)

### ISSUE THREAD

**Issue by tukao89** [tusdotnet/tusdotnet#178]
Hello, 

I try to deploy tusdotnet in docker (k8s) with multiple instances. I've read tus faq and using sticky session (in Load Balancer), It's work perfectly.
Anyone try to implement a lock (redis) as faq saying? https://tus.io/faq.html

Thanks.

**Comment by smatsson** [comment]
Hi,

Depending on your setup you might not need a lock in Redis. If each pod saves files locally the in-memory lock is sufficient given that sticky sessions work as expected. If using a shared file area you can disable sticky sessions and use disk based lock instead. See this wiki page https://github.com/tusdotnet/tusdotnet/wiki/Custom-File-Lock
