### ISSUE TITLE
ExpiredFilesCleanupService doesn't remove any files?

### ISSUE THREAD

**Issue by nmg196** [tusdotnet/tusdotnet#183]
Hi,
I've coped ExpiredFilesCleanupService into my project from the .NET 6 example and I've set expiration to 10 minutes in the "DefaultTusConfiguation" using the pattern from the same example:

`Expiration = new AbsoluteExpiration(TimeSpan.FromMinutes(10)),`

But although the job runs correctly, no files actually get deleted. How do I find out why it thinks there are no files to be deleted? 

The log files just show this line: .ExpiredFilesCleanupService|Removed 0 expired files. Scheduled to run again in 600000 ms

The folder it saves to has several months' worth of files in it:

![image](https://user-images.githubusercontent.com/8134047/185178183-dd672558-7502-49a2-9884-81b41d05140e.png)

Thanks!

**Comment by nmg196** [comment]
Ahh OK - I've just realised that this method cannot find any existing files as they won't have a <guid>.expiration file so it will only work to clean up files created **after** I added the expiration.

**Comment by nmg196** [comment]
Update: No that wasn't it. It's not removing files even if they have

**Comment by smatsson** [comment]
Hi,

Simplest question first: Did you use the correct format? E.g. `2022-05-27T12:42:47.6330329+00:00` in the .expiration file?

**Comment by nmg196** [comment]
I didn't create (or edit) the .expiration files. They are created automatically by the library when you set the expiration policy as per this line from my original post:

`Expiration = new `AbsoluteExpiration(TimeSpan.FromMinutes(10)),`

The .expiration files however do contain dates which look correct to me:
2022-08-23T12:48:55.0804287+00:00

**Comment by smatsson** [comment]
Okay that's my bad. I interpreted it as you created the file yourself. Could it be that the file is already completely uploaded? The `RemoveExpiredFilesAsync` method only removes files that are incomplete and have expired.

**Comment by nmg196** [comment]
Ahh it seems I've misunderstood then -  I was assuming that this folder was for temp files. I store the file as an Azure Blob after upload so what do I need to do to ensure the folder doesn't get infinitely big? Delete them with my own process after saving to Azure?

**Comment by nmg196** [comment]
Ahh it seems I've misunderstood then -  I was assuming that this folder was for temp files. I store the file as an Azure Blob after upload so what do I need to do to ensure the folder doesn't get infinitely big? Delete them with my own process after saving to Azure?

**Comment by smatsson** [comment]
That's understandable. :) See this wiki page on how to delete files: https://github.com/tusdotnet/tusdotnet/wiki/Deleting-processed-files-when-upload-is-complete
