### ISSUE TITLE
Custom Location Header

### ISSUE THREAD

**Issue by kallebysantos** [tusdotnet/tusdotnet#189]
I'm working in a project that I need to generate a presigned Url for upload and would be nice if was possible to send a custom `Location` header with client query params. The actual behavior of tusdotnet is call `SetReponseHeaders` after file creation so is no possible to override the generated Location.

For exemple:
1.  Client send and request to my API endpoint 
2. Then my API with validate the user grants and return a presigned upload url, like that `https://localhost/upload?token=12345`
3. Client do a tus upload to the presigned url given from API
4. My tus server will  keep it on Location header, like that `Response.Location = $"/upload/{ctx.fileId}?token=12345" `
5. So that when my client can continue the PATCH requests to the Location response with presigned params
6. Then `OnFileCompleteAsync` my tus server can have access to client query params and do some insert based on token data

Would be nice to have the concept above, where tus server can keep or customize the final Location header.
I'm already using a similar approach that I send the token on a `Upload-Token` header, but custom Location headers will give more control for server.

**Comment by smatsson** [comment]
Hi! 

This feature is planned for #147. Not really sure when it will be released so if you are in a hurry to get this to work you can use the `OnStarting` method on the `HttpResponse` to modify the header.

```
OnCreateCompleteAsync = ctx =>
{
    ctx.HttpContext.Response.OnStarting(() =>
    {
        ctx.HttpContext.Response.Headers.Location = new StringValues($"/uploads/{ctx.FileId}?token=12345");
        return Task.CompletedTask;
    });


    logger.LogInformation($"Created file {ctx.FileId} using {ctx.Store.GetType().FullName}");
    return Task.CompletedTask;
}
```

**Comment by smatsson** [comment]
tusdotnet 2.7 is now on nuget which supports this feature.

```csharp

OnCreateCompleteAsync = ctx => 
{
    ctx.SetUploadUrl(new Uri("/example/" + ctx.FileId);
    return Task.CompletedTask;
}

```

**Comment by kallebysantos** [comment]
Very thanks ✌️✌️

**Comment by smatsson** [comment]
Docs can be found here: https://github.com/tusdotnet/tusdotnet/wiki/Modify-the-upload-url-returned-to-the-client

**Comment by kallebysantos** [comment]
@intobrackets Can you describe in more detail what you need to do?
In my case, I developed a GraphQL Api and used tus to handle uploads. But for my application it was necessary to append `query params` to the `Location` header in order to keep the token value during the process.
That token was JWT based and I used to hold the form payload, so after the upload was complete I used that payload to perform an insert into the database.

Here is a code snippet of my app use case:
```csharp
// Program.cs
var path = "/api/upload";

app.UseTus(
    httpContext =>
        new DefaultTusConfiguration
        {
            UrlPath = path,
            Store = new TusDiskStore(storePath),
            Events = new Events
            {
                  OnCreateCompleteAsync = (ctx) =>
                  {
                      var queryParams = ctx.HttpContext.Request.QueryString.ToString();
                      var locationUri = new StringValues($"{path}/{ctx.FileId}{queryParams}");
                  
                      ctx.HttpContext.Response.OnStarting(() =>
                      {
                          ctx.HttpContext.Response.Headers.Location = locationUri;
                          return Task.CompletedTask;
                      });
                  
                      return Task.CompletedTask;
                  }
             }
       }
 );
```
The example above describes how I'm changing the `Location` header to keep my `token=`  value, prefer use `ctx.SetUploadUrl( )` instead manually change via `ctx.HttpContext.Response.OnStarting( )` like I did.
> Note that I don´t change the final Uri path, only append query params to it. In your example you're rewriting your URI to `/files/<tasksFolder:uuid>/<ctx.FileId>`, in your case the `ctx.FileId` is returning the `filename` instead of `uuid` probably you make some overwriting or bad configuration.


```csharp
// FileMutation.cs
    public PresignedUploadResult? GetPresignedUpload(
        [Service] IHttpContextAccessor httpContextAccessor,
        [Service] IOptions<AppSettings> settingsProvider,
        PresignedUploadType presignedPayload
    )
    {
        var settings = settingsProvider.Value;
        var baseUri = new Uri(WebHelper.GetBaseUri(httpContextAccessor) ?? string.Empty);

        /* Do some validation Here*/

        var token = TokenHelper.WriteToken(
            secret: settings.UploadJWTSecret,
            expires: settings.UploadExpirationSeconds,
            values: presignedPayload
        );

        var uploadUri = new Uri(baseUri, "/api/upload");

        var uploadUriWithQuery = QueryHelpers.AddQueryString(
            uri: uploadUri.ToString(),
            name: nameof(token),
            value: token
        );

        if (string.IsNullOrEmpty(uploadUriWithQuery))
        {
            throw new RouteCreationException("Could not create the upload route");
        }

        return new(uploadUriWithQuery);
    }
```
The example above represents my GraphQL mutation function, this function will handle a Input payload and then return a preassigned url that points to my tus endpoint, the result will be like:
```json
{
	"data": {
		"presignedUpload": {
			"url": "http://localhost:5000/api/upload?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJjNzZlYzlmZS05MjI4LTQ3NjgtODVhYS02NGI2MmUzMWIyMDIiLCJGb2xkZXJJZCI6IjhlYmY3NjZjLWFlMDctNDlhMy1hMzQxLWIzMzAxNThjZmEzZSIsIkZpbGVOYW1lIjoiYXVsYV8xLm1wNCIsIm5iZiI6MTY4MzYyNzEzNywiZXhwIjoxNjg0MjMxOTM3LCJpYXQiOjE2ODM2MjcxMzd9.P2kEDoS-vM52XBqRTVCA_AFtDP_1AbVynw3-0sGOPvg"
		}
	}
}
```
Then I use the `url` value inside my frontend tus client (Uppy or any other).

**Comment by intobrackets** [comment]
Thank you @kallebysantos for your reply.
I am using Tus (Uppy with Tus on Front + Tusdotnet + [Xtensible.TusDotNet.Azure](https://github.com/giometrix/Xtensible.TusDotNet.Azure) on the Back)  to upload files and sotre it into Azule Blob Storage
- Why i tried to change the location ?
=> i would like to sotre every uploaded file to a sub folder on the blob container, because, by default it store files to the root container folder.
I hope to have been clear.
Thanks in advance.
