### ISSUE TITLE
Tus in Github Actions / Docker?

### ISSUE THREAD

**Issue by SebastianStehle** [tusdotnet/tusdotnet#191]
Hi,

I have a weird question. I am not sure if you can answer it, but perhaps you have experienced the problem before. 

Yesterday my tests started failing in Github actions: https://github.com/Squidex/squidex/actions ... I have not changed anything in the backend, so it is very strange. I have a few tests with tus and 2 of these tests also continue the upload process: https://github.com/Squidex/squidex/blob/feda83fdb86f7336456c3da646b9af6c23c16474/backend/tools/TestSuite/TestSuite.ApiTests/AssetTests.cs#L74

it works 100% of the time locally. I have used the loop to test 1000 iterations. But in Github actions I get a 409 multiple times. My assumption is that something with the locks does not work properly. Perhaps the lock files do not get deleted correctly. I run the backend in docker, so there is nothing special.

**Comment by SebastianStehle** [comment]
Okay, stupid question. I just realized that the default lock provider is in-memory.

**Comment by smatsson** [comment]
Not a stupid question at all. I'm not that familiar with Github actions but had similar issues in the tusdotnet test project when running tests in parallel. Ended up using this code which is basically a lock per object instance. https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet.test/Helpers/TestServerInMemoryFileLockProvider.cs

**Comment by SebastianStehle** [comment]
The problem was something different:

My previous test was looking like this:
https://github.com/Squidex/squidex/blob/c925d48fa2aecfdbd0cadb3f229d3e686558efd8/backend/tools/TestSuite/TestSuite.ApiTests/AssetTests.cs#L73

So I have built a custom stream which was "pausing" to deliver content after X % with an exception: https://github.com/Squidex/squidex/blob/c925d48fa2aecfdbd0cadb3f229d3e686558efd8/backend/tools/TestSuite/TestSuite.ApiTests/AssetTests.cs#L729

The problem was that the HTTP request was in a weird state, it was still ongoing on the backend for a little bit of time. In my local development only for a < 1ms, because I had never problems with that, but in docker it was relatively long. Perhaps due to the proxies (caddy). So when the next chunk was about to be uploaded it very often failed with a 409. Even after 500ms this was still not resolved and of course you do not want to make your tests dependent on timing.

The final stream does not throw an exception anymore but just stops after X% and only reports the correct length:
https://github.com/Squidex/squidex/blob/master/backend/tools/TestSuite/TestSuite.ApiTests/AssetTests.cs#L713

But I had to update my client code so that I could overwrite the content length, which was before just derived from the stream length.

**Comment by smatsson** [comment]
Glad you solved it! Seems likely that a reverse proxy would cause this.

While you're here: I must say I'm very impressed with your AssetTusRunner. It's a cool idea and neat implementation. There has been some previous discussions on how to do something similar in tusdotnet so I have started #194 to make it possible. No ETA yet but hopefully any year now ;)
