### ISSUE TITLE
Client disconnect not recognized on linux machine

### ISSUE THREAD

**Issue by FVillebro** [tusdotnet/tusdotnet#197]
I am using **MapTus** to add file uploading to my dotnet backend, which is dockerized and deployed in a linux environment.

Everything is working great as I can pause and start again etc. However, if I disconnect the ethernet adapter on the client side while uploading and enable it once again all requests to continue results in error 409. It has been really frustrating to troubleshoot because if I deploy the exact same docker container on my local windows machine and disconnects it the same way it continues like nothing happened afterwards.

I investigated and found that the error is due to the **FileLock** not being released. In the windows enviroment the **FileLock** is released as soon as it detects the client is disconnected. This is not the case for the linux environment as it is never detected that the client is disconnected. 

As far as I can tell the **ClientDisconnectGuardedPipeReader** is responsible for detecting when a client is disconnected in my case.  To resolve the issue I added a **CancelationTokenSource** with a timeout in the **GuardedPipeReaderFactory** and pass the token to the reader. This is not an optimal solution, so I would be happy if it could be resolved some other way.

**Comment by smatsson** [comment]
Hi! This is a known issue when running directly on Kestrel without a reverse proxy. The `ClientDisconnectGuardedPipeReader` handles some cases but is still dependent on somehow knowing that the connection has been cancelled. See earlier issue on the same thing with a work around: https://github.com/tusdotnet/tusdotnet/issues/156#issuecomment-979348495

**Comment by FVillebro** [comment]
Thanks for the response! You mention the problem is due to connecting directly to Kestrel. However, I am using a reverse proxy (traefik), but maybe it doesn't have a request timeout set by default. I'll look into it.

**Comment by smatsson** [comment]
Please do and let me know what you find out :) It doesn't necessarily need to be that traefik does not support request timeouts (really idle timeouts). It might be that it does but does not notify the backend service which would end up being the same issue from tusdotnet's point of view.  I think this might be worth fixing once and for all in tusdotnet. The last time this was brought up I considered it an issue with Kestrel but if it's a real issue with other reverse proxies it would be a good idea to add a read timeout in this project too, similar to how you implemented the workaround.

**Comment by lwahonen** [comment]
This definitely should get documented better, if not outright fixed.

Right now, the sample from the front page of the repo doesn't actually support one of the key features tus (transparent upload resume on unreliable networks).

**Comment by smatsson** [comment]
@lwahonen While I agree with you that this could be a good improvement to tusdotnet and it's on the todo list, this part is just false:
>Right now, the sample from the front page of the repo doesn't actually support one of the key features of tus (transparent upload resume on unreliable networks).

The example works perfectly well as long as you have a RP that follows the http spec. 

If you need the feature quickly, feel free to submit a PR that fixes the code or send a PR in [this repo](https://github.com/tusdotnet/tusdotnet.wikisource) for the changes to docs.

**Comment by lwahonen** [comment]
I think this is mostly a documentation issue, not a code fix issue. The .net 6.0 sample app doesn't actually do the transparent upload unless you have a reverse proxy in front of it, but the need for that transparent proxy isn't really mentioned anywhere.

**Comment by smatsson** [comment]
@lwahonen That's a very valid point that I overlooked. I have updated the wiki and the readme to include more info on configuring Kestrel and/or reverse proxies. Ideally I would like this automatically solved within tusdotnet but I don't really have the time to invest right now. Please let me know if the docs are now better (or possibly worse) :)

**Comment by lwahonen** [comment]
Looks much better in my opinion. Just trying to make sure nobody gets bitten by this one, as it’s easy to avoid if you know how :)

**Comment by smatsson** [comment]
It's very much appreciated :)

**Comment by smatsson** [comment]
A new configuration setting to handle timeouts now exists in [tusdotnet 2.8](https://www.nuget.org/packages/tusdotnet/2.8.0). See `ClientReadTimeout` [on this wiki page](https://github.com/tusdotnet/tusdotnet/wiki/Configure-tusdotnet)
