### ISSUE TITLE
Please add a way to limit the chunk size

### ISSUE THREAD

**Issue by sophisma** [tusdotnet/tusdotnet#199]
Currently we can limit the maximum size of a file using MaxAllowedUploadSizeInBytesLong or MaxAllowedUploadSizeInBytes.
If we want to limit the chunk size we have to rely on configuration on the client side, which is not very wise.

**Comment by smatsson** [comment]
What issue are you experiencing that limiting the chunk size on the server would solve?

**Comment by sophisma** [comment]
Imagine that you have a situation where you're using Uppy + Tus to upload files to the server.
Let's say you configure the server to receive files with a maximum size of 4GB.
On the client side you can currently configure Uppy + Tus with a maximum file size, maximum chunk size and maximum number of concurrent uploads. Let's say that the clients maliciously change their chunksize to 2GB, what happens to the server's memory? And yes, I know you can configure this stuff on the server. But what if the server requires a bigger request size for other applications?
Another scenario would be if you want to support multiple tiers of service for different clients (free vs paid accounts).

**Comment by smatsson** [comment]
I think there are some misconceptions and odd assumptions in this thread.

>On the client side you can currently configure Uppy + Tus with a maximum file size, maximum chunk size and maximum number of concurrent uploads. Let's say that the clients maliciously change their chunksize to 2GB, what happens to the server's memory?

Nothing as tusdotnet does not keep the entire chunk in memory.

>But what if the server requires a bigger request size for other applications?

Could you give me an example where the server requires a bigger request size for non-resumable uploads than it does for resumable uploads? It seems like a stretch. If you still need this you can limit the request size and [just disable it](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.disablerequestsizelimitattribute?view=aspnetcore-7.0) for whatever endpoint that needs it.

**Comment by sophisma** [comment]
> I think there are some misconceptions and odd assumptions in this thread.
> 
> > On the client side you can currently configure Uppy + Tus with a maximum file size, maximum chunk size and maximum number of concurrent uploads. Let's say that the clients maliciously change their chunksize to 2GB, what happens to the server's memory?
> 
> Nothing as tusdotnet does not keep the entire chunk in memory.

How is the amount of data sent from the client to the server, in each request, defined?

> > But what if the server requires a bigger request size for other applications?
> 
> Could you give me an example where the server requires a bigger request size for non-resumable uploads than it does for resumable uploads? It seems like a stretch. If you still need this you can limit the request size and [just disable it](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.disablerequestsizelimitattribute?view=aspnetcore-7.0) for whatever endpoint that needs it.

Let's say you have two applications running on the server. 
Application A does not support resumable uploads and requires you to upload files with a maximum size of 4MB (sent using a standard form with enctype='multipart/form-data').
Application B supports resumable uploads with Uppy + Tus with a chunk size of 100Kb (we already established that the chunk size is not what defines the amount of data sent in each request, please replace it with the correct term).

**Comment by smatsson** [comment]
> How is the amount of data sent from the client to the server, in each request, defined?

https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Stores/TusDiskStore.cs#L89
https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Stores/TusDiskStore.PipeReader.cs#L40

> Let's say you have two applications running on the server.

I'm sorry but I don't really follow the reasoning here. Could you elaborate on how this would work and why you need it? I thought the issue was that you didn't want to use to much memory on the server which is not an issue as pointed out above. 


  There have been some discussions to add this feature to the protocol but there hasn't been any new updates to it in a while. For a feature like this to be useful it needs to be understood by both the server and the client so that the client knows what to expect. See https://github.com/tus/tus-resumable-upload-protocol/pull/93

**Comment by sophisma** [comment]
Ok, I'll try to do this in a different way.
What are your thoughts on allowing the developers to adjust this value (to a lower value)?

`const int JUST_BELOW_LOH_BYTE_LIMIT = 84 * 1024;`

And you're right, eventually the protocol has to change so both client and server understad each other.

**Comment by sophisma** [comment]
> I'm sorry but I don't really follow the reasoning here.

Ok, let me try this differently. 
Just to give a bit of context, I misused the word chunk in the title and original post.  Please keep in mind that when I use the work "chunk" I mean the block of data being transferred in each HTTP request, not the chunk file on the disk that is partially filled by those requests. I realised this a few posts back but I don't think you did. Just wanted to clarify it.
Imagine this scenario, let's say you have a file download server, where people can download large files.
Your application starts to grow in user count and you start getting a lot of parallel requests. So now you have to figure out a way to serve more files in parallel. 
For argument sake let's say that your server has a 10Mb/s connection and previously each "chunk" sent to the client had 5Mb , so you could serve two clients simultaneously.
Now your application grew to 10 clients. One thing you can do is, instead of serving 5Mb of data to each client, is send them 1Mb "chunks", so you can serve the 10 clients simultaneously. With this you can better manage your server's bandwidth (and memory).
What I'm asking is the possibility to do this with Tus, to limit how much data a user can send in each request.
You're absolutely right when you say that that probably requires changes to the protocol. Initially the server has to announce the maximum size allowed and if the client sends more data than allowed it should throw an error.

**Comment by sophisma** [comment]
I faven't had too much time to look at the code you sent but in TusDiskStore there's this line:

`const int JUST_BELOW_LOH_BYTE_LIMIT = 84 * 1024;`

What are your thoughs on allowing the developer to define a lower value here?

**Comment by smatsson** [comment]
Sorry to be frank here but is this a real world issue or just some theoretical issue? I don't have the time nor energy to debate hypotheticals.

> What are your thoughs on allowing the developer to define a lower value here so that the buffer size and "chunk" size match?

I don't really see the point though. The constant is used to create an array inside the FileStream used for writing the file to disk. This is the maximum value that can be used per write and it was chosen to not go over the Large Object Heap (LOH) limit as this might cause "memory leaks" (not really, but the GC will compact the LOH space less). The internals of the FileStream uses an ArrayPool so the number of allocations is basically non existing. The LOH limit was chosen for the edge case where the ArrayPool is full. In this case a new array will be allocated and this is when we do not want to put that array into the LOH. 

I think what you are looking for is the `TusDiskBufferSize` class. This class allows you to specify the write buffer size in bytes. The lower the value the less memory is consumed. On the other hand the more IO and CPU will be required to handle the writes.

**Comment by sophisma** [comment]
> Sorry to be frank here but is this a real world issue or just some theoretical issue? I don't have the time nor energy to debate hypotheticals.
> 
Real world scenario.
If you don't have energy to debate I think I'll leave at this.
Thank you for your attention anyway.

**Comment by smatsson** [comment]
>Real world scenario.
> If you don't have energy to debate I think I'll leave at this.

You are reading that wrong. I said that I have no energy to discuss *hypotheticals*. We are 10 messages in and I still have no idea what problem you are trying to solved. You started with a XY problem about chunk sizes and then somehow pivoted to bandwith and then grasping at straws for things to change without understanding the code. 

What's the problem you are trying to fix?
