### ISSUE TITLE
How to configure to upload viemo api

### ISSUE THREAD

**Issue by reoq22** [tusdotnet/tusdotnet#200]
I want to upload a large video to Vimeo using Vimeo API upload endpoint instead of keeping files in local disk `"App_Data", "tusfiles"` does anyone have any idea?

**Comment by smatsson** [comment]
Vimeo already supports tus 1.x natively so no need to involve tusdotnet at all. You can just send the data directly to Vimeo from your client. 

https://developer.vimeo.com/api/upload/videos

**Comment by reoq22** [comment]
Thank you so much  I am very beginner to use Tus.
