### ISSUE TITLE
Expired Files Cleanup Service on multiple folder

### ISSUE THREAD

**Issue by benny-adiwijaya** [tusdotnet/tusdotnet#203]
Hi, I like the idea to have different upload paths for different users https://github.com/tusdotnet/tusdotnet/issues/56#issuecomment-473202921 
It will create multiple folder. How to configure Expired Files Cleanup Service with multiple folder? can it be set to root path and recursive to all folder?

**Comment by smatsson** [comment]
Hi! 

The expired files cleanup service is not part of the library. It was written as an example on how to periodically cleanup files. If you read the [source code](https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_net6.0_TestApp/Services/ExpiredFilesCleanupService.cs) for it you can see that all it does is periodically call the `ITusExpirationStore` provided to it. 

What you need to do is to rewrite it to list all directories of the root folder, create a `TusDiskStore` for each of the directories found and then run the method to cleanup expired files.
