### ISSUE TITLE
409 http status code when trying to resume upload after broken connection

### ISSUE THREAD

**Issue by raV720** [tusdotnet/tusdotnet#204]
I get error 409 conflict when trying to resume upload after broken connection and response body:
`File 5130a58664bf453b9323a1babded973e is currently being updated. Please try again later`
I guess it is from:

https://github.com/tusdotnet/tusdotnet/blob/b1915bc4a9584504ba6e40b51ebc287ec7443d93/Source/tusdotnet/Runners/TusV1EventRunner.cs#L62 

Is it expected behavior?
For me it seems there is file lock not released. After restarting service the broken upload is resumed and finished with success. I can see the lock also prevents from deleting file using **TusDiskStore.RemoveExpiredFilesAsync()**
Can I use **tusdotnet.Stores.TusDiskStore** as singleton in entire asp net core app or I have to create instance per request?

The TUS configuration:
```
app.MapTus("/api/files", async httpContext => new()
            {
                Store = new tusdotnet.Stores.TusDiskStore(StoragePath + '/', true),
                Events = new()
                {
                    OnFileCompleteAsync = async ctx =>
                    {
                        logger.Info($"File transfer completed. FileId: {ctx.FileId}");
                    }
                },
                Expiration = new SlidingExpiration(TimeSpan.FromMinutes(10))
            });
```

**Comment by raV720** [comment]
@smatsson It seems a bug for me. Can you explain why the lock is not released?

**Comment by smatsson** [comment]
This is a known issue on some configurations. Work around can be found here: https://github.com/tusdotnet/tusdotnet/wiki/Configure-Kestrel

**Comment by smatsson** [comment]
> Can I use tusdotnet.Stores.TusDiskStore as singleton in entire asp net core app or I have to create instance per request?

You can use it as singleton as long as you are using the same disk path to save files to.

**Comment by raV720** [comment]
Thank you
