### ISSUE TITLE
Upload similiar file twice issue

### ISSUE THREAD

**Issue by benny-adiwijaya** [tusdotnet/tusdotnet#209]
Hi, when upload similiar file twice, OnUploadCompleteAsync is only fired once the first time the file is completed. Is there a way to notify user that those file already uploaded instead of upload successfull. My case is when different user trying upload similiar file with different metadata, user get notif upload successfull when the reality file and metadata not stored on system. Thank you

**Comment by smatsson** [comment]
I'm not sure what you mean by uploading a similar file? There is no such thing in the tus protocol. Each file would have it's own resource url returned by the intial POST to create the upload. If you are re-using resource urls between uploads you will most likely end up with data corruption.

> Is there a way to notify user that those file already uploaded instead of upload successfull

Yes, perform a HEAD request for the resource url and check if the `Upload-Length` and `Upload-Offset` headers are equal.

>My case is when different user trying upload similiar file with different metadata, 

Metadata is set per resource url when creating the resource, so this would probably not work as you expect. Not an expert on your use case thought so it might not mean tus metadata?

**Comment by benny-adiwijaya** [comment]
https://github.com/tusdotnet/tusdotnet/issues/17#issuecomment-300130333 In this topic you said OnUploadCompleteAsync is only fired once the first time the file is completed. Is this behavior still same? Because when I try to upload same file twice, sometimes successfully uploaded but sometimes the second attemp is not uploaded eventhough the response is upload successfull

**Comment by smatsson** [comment]
Hmm this sounds odd. The OnUploadCompleteAsync is only called once per resource url. I just verified this by creating a new file, uploading it completely and then trying again:

1. POST to /files -> Returns a new URL in the location header (the resource url)
2. PATCH to <location header from 1>
3. Once uploaded completely, OnUploadCompleteAsync is called
4. PATCH to <location header from 1>
5. Returned: 400 Bad Request with body "Upload is already complete."

When you say you are uploading the same file twice, is it the above flow you are using? Or are you creating a new resource url each time? What client are you using? What version of tusdotnet?

**Comment by benny-adiwijaya** [comment]
I am using Uppy on Client and tusdotnet version 2.7.1. I am not really sure if Uppy using the flow above. I am using default tusdotnet configuration. How to create new resource url on every upload?

**Comment by smatsson** [comment]
Uppy does use this flow as most clients do. Uppy will calculate a fingerprint of the selected file and store that fingerprint in local storage together with the resource url. When the same file is selected again (with a matching fingerprint) it will grab the resource url and do a HEAD request to check where to continue the upload. If the upload is already complete it will just show the upload as completed.

There's a setting in Uppy where you can remove the local storage fingerprint once the upload is completed. This will allow you to upload the same file multiple times. You should probably consider if this is what you wish to do as it requires the user to upload a potentially large file again (and also uses more disk space etc on the server). The setting is `removeFingerprintOnSuccess` like so: 
```
<script type="module">
    import { Uppy, Dashboard, Tus } from "https://releases.transloadit.com/uppy/v3.17.0/uppy.min.mjs"
    new Uppy()
        .use(Dashboard, { inline: true, target: 'body' })
        .use(Tus, { endpoint: 'https://localhost:5009/files', removeFingerprintOnSuccess: true })
</script>
```
