### ISSUE TITLE
Events OnBeforeDeleteAsync and OnDeleteCompleteAsync not firing

### ISSUE THREAD

**Issue by elf2k00** [tusdotnet/tusdotnet#213]
Subscribing to Events, all of them are fired as expected except OnBeforeDeleteAsync and OnDeleteCompleteAsync. Using the provided code samples to configure Tus.

```
OnBeforeDeleteAsync = ctx =>
{
   return Task.CompletedTask;
},
OnDeleteCompleteAsync = ctx =>
{
   return Task.CompletedTask;
},
```
The uploaded file is moved after completing. Tried using the `DeleteFileAsync` from the termination store to remove the files Tus created, files are deleted correctly but no Delete events are fired.

```
var terminationStore = (ITusTerminationStore)ctx.Store;
terminationStore.DeleteFileAsync(file.Id, ctx.CancellationToken);  
```

Also using the expiration cleanup for not completed files, these files are also removed when the scheduled task is launched, no OnDelete events are fired either

```
public TusExpiredFilesCleanupService(ILogger<TusExpiredFilesCleanupService> logger, DefaultTusConfiguration config)
{            
  _expirationStore = (ITusExpirationStore)config.Store;
  _expiration = config.Expiration;
}
[..]
var numberOfRemovedFiles = await _expirationStore.RemoveExpiredFilesAsync(cancellationToken);
```

According to the Delete events [description ](https://github.com/tusdotnet/tusdotnet/wiki/OnBeforeDelete-event)they should be fired on Delete requests.

**Comment by smatsson** [comment]
Hi!

I can see how this is confusing in the docs. Sorry about that! The events only fire when a _client_ does the request, not when you manually change stuff using the store. The idea is to be able to determine if a client has access to a particular feature at this time, e.g. the client might not be allowed to delete the file while it is being processed. 

I will update the documentation to make this clearer. The same applies for OnBeforeCreate/OnCreateComplete when manually creating files and OnFileComplete if for any reason you would write data to a file manually.

**Comment by smatsson** [comment]
I have updated the wiki to make more sense in this regard. Thanks for reporting!
