### ISSUE TITLE
Update to .NET 8

### ISSUE THREAD

**Issue by SebastianStehle** [tusdotnet/tusdotnet#215]
Hi,

I am using this library but for .NET 8 it is not compatible anymore (something with the System.*.Headers package that is not compatible with .NET 6 anymore).

Would you make an update or do you need a PR?

**Comment by smatsson** [comment]
What error are you getting? I just tested to change the ASP.NET Core 6 site to `<TargetFramework>net8.0</TargetFramework>` and did not get any errors and the file was uploaded just fine?

**Comment by SebastianStehle** [comment]
Sorry, it was my fault, I have misinterpreted the error. Everything is fine
