### ISSUE TITLE
UseTus or MapTus?

### ISSUE THREAD

**Issue by urza** [tusdotnet/tusdotnet#217]
Hi, this might be a silly question, but on your readme page example, there is
`app.MapTus` method and in the [wiki ](https://github.com/tusdotnet/tusdotnet/wiki/Processing-a-file-once-the-file-upload-is-complete) there is `app.UseTus ` method.

What is the difference between them, which should I use?

**Comment by smatsson** [comment]
Hi! 

Not silly at all, I understand the confusion :)

The recommended way is using `app.MapTus` as it is newer and integrates into ASP.NET Core endpoint routing which gives you automatic support for route patterns, authorization etc.

There are some docs on the wiki discussing the differences: https://github.com/tusdotnet/tusdotnet/wiki/Configure-tusdotnet#endpoint-routing-or-middleware

**Comment by urza** [comment]
Cool, thanks for the explanation.
