### ISSUE TITLE
How to implement file encryption?

### ISSUE THREAD

**Issue by wbz-hot** [tusdotnet/tusdotnet#218]
I want to encrypt files during upload and store them locally or on AWS. I would like to know where and how to perform symmetric encryption with CBC.

**Comment by smatsson** [comment]
Hi! 

For local disk storage it is recommended to use full disk encryption on the OS level. For AWS you will need to implement your own store: https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store

**Comment by wbz-hot** [comment]
Thank you for your response. I have customized storage to receive files using the Tus protocol first, and then I encrypt them before uploading to AWS.
