### ISSUE TITLE
Possibility to override or re-set the Store Path value on the event

### ISSUE THREAD

**Issue by MGAjinugrh** [tusdotnet/tusdotnet#219]
Hi, I am new to the tus protocol.

Currently I am building an upload mechanism using the tus-js-client and tusdotnet on the backend to a replacement for the existing upload module in my solution.

Previously in my old upload mechanism, we determine the destination of the file upload based on the query parameter from the HttpContext object when we send the request. Can we achieve similar things here? My end goal here is to be able to have dynamic upload file destination using the values of HttpContext query parameters on every upload requests so I could avoid multiple copy process (having one more step to copy from the tus configured Store path into the actual dynamic destination path defined in the HttpContext query parameters which is a redundant step).

Code to illustrate my end goal :

```
app.UseTus(context => new DefaultTusConfiguration
{
	UrlPath = "/files",
	Store = new TusDiskStore(@"C:\tusfiles\"), //I want to override or re-set the value per every upload requests
	Events = new Events
	{
		OnBeforeCreateAsync = ctx => //Trying to find the initial event that gets called when we send upload request (cmiiw)
		{
                        string uploadDir = GetUploadStoreDir(eventCtx.HttpContext.Request.Query);
                        ctx.Store = GetUploadDir(eventCtx.HttpContext.Request.Query); //re-set the value here
                        if (!Directory.Exists(Path.GetFullPath(uploadDir))) Directory.CreateDirectory(uploadDir);
                        
			return Task.CompletedTask;
		},
		OnFileCompleteAsync = async eventContext =>
		{
			// eventContext.FileId is the id of the file that was uploaded.
			// eventContext.Store is the data store that was used (in this case an instance of the TusDiskStore) //how can I use the same dynamic value?

			// A normal use case here would be to read the file and do some processing on it.
			ITusFile file = await eventContext.GetFileAsync();
			var result = await BuildFilePlacementAsync(file, eventContext.Store);

			if (!result.Success)
			{
				throw new MyProcessingException("Something went wrong during processing");
			}
		}
	}
});
```

GetUploadDir is a method that will give us the destination for the file upload.

**Comment by smatsson** [comment]
Hi,

The disk path needs to be consistent between requests for the store to find the file and be able to continue the upload if the connection breaks down. What you are asking for can be achieved by setting the path in the configuration factory as below. 

```csharp
app.UseTus(async httpContext =>
{
    var diskPath = GetDiskPath(httpContext.Request.Query);

    return new DefaultTusConfiguration
    {
        UrlPath = "/files",
        Store = new TusDiskStore(diskPath),
        Events = new Events
        {
            OnCreateCompleteAsync = async ctx =>
            {
                // tusdotnet will automatically create a url in the form of "/files/<file id>" but since we also need
                // the folder param here we need to add it to the url
                ctx.SetUploadUrl(new Uri($"/files/{ctx.FileId}?folder=somevalue", UriKind.Relative));
            },
            OnFileCompleteAsync = async eventContext =>
            {
                // Do stuff
            }
        }
    };
});

string GetDiskPath(IQueryCollection query)
{
    return Path.Combine("whatever", "folder", query["folder"]);
}
```

**Comment by MGAjinugrh** [comment]
Hi thanks for the suggestion! currently it worked like a charm!

However, I couldn't help but noticed few things while debugging.

1. The instance (where we generate the tus configuration) seems to be triggered periodically by the system whether we are trying to send the request to upload the file or not. My hunch is that this happens since the tusdotnet itself is set as a middleware in the startup (cmiiw).
2. Because of point number 1, it gives me the impression that in the middle of upload, the configuration got re-configured and since it's not coming from the upload request, the value of Store object is set with new TusDiskStore(string.Empty).
3. Why do we need to set the httpContext, ctx , and eventContext to asynchronous? Because in my actual code I don't have any calls for asynchronous function inside of the events thus it gives me warning CS1998: This async method lacks 'await'.

**Comment by smatsson** [comment]
Great! Glad it's working for you :) 

These are all good questions!

>The instance (where we generate the tus configuration) seems to be triggered periodically by the system whether we are trying to send the request to upload the file or not. My hunch is that this happens since the tusdotnet itself is set as a middleware in the startup (cmiiw).

Yes this is how the middleware approach works. If possible I would recommend to change `UseTus` to `MapTus` to have it integrate into endpoint routing in ASP.NET Core. This gives you some advantages, such as integration with authorization. See https://github.com/tusdotnet/tusdotnet/wiki/Configure-tusdotnet#endpoint-routing-or-middleware for more details.

> Because of point number 1, it gives me the impression that in the middle of upload, the configuration got re-configured and since it's not coming from the upload request, the value of Store object is set with new TusDiskStore(string.Empty).

Exactly right. The config returned is used to determine if tusdotnet should run for the request or not. Since the URL path won't match it won't run and the rest of the config is not used.

> Why do we need to set the httpContext, ctx , and eventContext to asynchronous? Because in my actual code I don't have any calls for asynchronous function inside of the events thus it gives me warning CS1998: This async method lacks 'await'.

There's no need for it to be async. I just added it to not be forced to wrap the config in `Task.FromResult` to make it easier to read.
