### ISSUE TITLE
bug: write custom data to the response fails with error

### ISSUE THREAD

**Issue by mahdighorbanpourptw** [tusdotnet/tusdotnet#220]
Hi,
I would like to write some custom json response on the event OnFileCompleteAsync. However, I get the an error.  Here is how to reproduce it in the example code "AspNetCore_net6.0_TestApp->Program.cs Line 176":

![image](https://github.com/tusdotnet/tusdotnet/assets/97948692/0e9b2b0b-6d6b-4a7c-b394-4166426ae36e)

And this will be the error:
![image](https://github.com/tusdotnet/tusdotnet/assets/97948692/90b9f55f-9bfc-40a1-8baa-c806c50e0e8b)

And here is how to fix the error in file TusEndpointInvoker.cs line 61. Unfortunately I was not able to push it myself. Adding one if case will fix the issue. Would that be possible to apply the fix in the next release? Thank you

![image](https://github.com/tusdotnet/tusdotnet/assets/97948692/0884cbb9-bb1f-4965-9563-534d5cc791a9)

**Comment by smatsson** [comment]
>I would like to write some custom json response on the event OnFileCompleteAsync. However, I get the an error. Here is how to reproduce it in the example code "AspNetCore_net6.0_TestApp->Program.cs Line 176":

The tus protocol is very strict on the response code of the PATCH call that writes the file, `204 No Content`. I.e. you cannot set a body. If you need to return data to the client, use either a header or save the response somewhere and add a [Content-Location](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Location) header

> And here is how to fix the error in file TusEndpointInvoker.cs line 61. Unfortunately I was not able to push it myself. Adding one if case will fix the issue. Would that be possible to apply the fix in the next release? Thank you

This fix would break compatibility with pretty much every client out there as they expect a specific status code and specific http headers to be returned. It would _maybe_ be possible to allow custom responses but there is no guarantee that it works with available clients.

**Comment by mahdighorbanpourptw** [comment]
@smatsson Thank you for the quick response and clarification. 

> This fix would break compatibility with pretty much every client out there as they expect a specific status code and specific http headers to be returned. It would maybe be possible to allow custom responses but there is no guarantee that it works with available clients.

This sounds like an idea! 

> This fix would break compatibility with pretty much every client out there as they expect a specific status code and specific http headers to be returned. It would maybe be possible to allow custom responses but there is no guarantee that it works with available clients.

I believe this fix will not break any of the clients. This fix only allows writing custom response, but no one is writing the custom response, then nothing is broken. If someone wants to write custom response in the backend side, they will also fix/adapt the frontend part! Just give it a second thought, please. I will close the issue anyway! Thank you again.
