### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by KhaledSMQ** [tusdotnet/tusdotnet#24]
Hi, I would like to thank you for tus project,
 how i can validate the file before upload?

**Comment by smatsson** [comment]
Hi Khaled,

There is currently no built in way of validating a file before uploading.
The original idea was to keep "extra features" (such as validation and
authorization) out of tusdotnet to keep it lean. We might need to rethink
this though :)

What kind of validation do you require? Is checking the Metadata good
enough or do you also need to check the file content?

**Comment by smatsson** [comment]
I'll close this issue as there has been no answers to my follow up questions in 11 days. I have added a page to the wiki which describes how to accomplish validation of metadata before a file is created. https://github.com/tusdotnet/tusdotnet/wiki/Validate-metadata-before-creating-a-file

**Comment by smatsson** [comment]
@KhaledSMQ A new way of validating files will be shipped with tusdotnet 2.0. The issue can be found at https://github.com/tusdotnet/tusdotnet/issues/33

**Comment by KhaledSMQ** [comment]
@smatsson Thank you so much for the effort  and time you spend working on tus it's just amazing.
