### ISSUE TITLE
Exceptions in OnUploadCompleteAsync

### ISSUE THREAD

**Issue by uoziod** [tusdotnet/tusdotnet#28]
I realized that all exception happening in OnUploadCompleteAsync are silent and the application continues to work. Is there any chance to handle them and pop higher custom responses?

**Comment by uoziod** [comment]
Is there any way of gently replacing TusOwinMiddleware by something custom?

**Comment by smatsson** [comment]
@uoziod I'm not really sure what you are asking. tusdotnet does _not_ silently handle exceptions in OnUploadCompleteAsync. To handle the exception you must specify an exception handling middleware like @SasaCetkovic said. See example here: https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/OwinTestApp/Startup.cs#L49

For the second question, no there is no simple way of replacing the entire middleware as the classes for handling the protocol are internal. You could possibly use reflection but that is in no way supported.

**Comment by smatsson** [comment]
@uoziod Did the code example in the link above solve your problem? Feel free to comment again otherwise :)

**Comment by smatsson** [comment]
@uoziod I'll close this due to inactivity. Feel free to create a new issue with any further questions.
