### ISSUE TITLE
Access metadata on OnFileCompleteAsync 

### ISSUE THREAD

**Issue by KhaledSMQ** [tusdotnet/tusdotnet#39]
It will be great if i can access Metadata OnFileCompleteAsync context to insure saving data i have sent from the front-end to back-end after the file uploaded.
there is any way to tweak this

**Comment by smatsson** [comment]
Hi @KhaledSMQ 

You can already achieve this as you have access to the store. Cast the store to the ITusCreationStore interface and use GetUploadMetadataAsync method to get the raw metadata. Then parse it using the tusdotnet.Models.metadata model. I want to keep the callback context's as lean as possible and not load data that might not be needed. 

```
OnCreateCompleteAsync = async ctx =>
                    {
                        var metadataString = await ((tusdotnet.Interfaces.ITusCreationStore) ctx.Store).GetUploadMetadataAsync(ctx.FileId, ctx.CancellationToken);
                        var metadataDict = tusdotnet.Models.Metadata.Parse(metadataString);

                        var myValue = metadataDict["myKey"].GetString(Encoding.UTF8);
                        //var myValue = metadataDict["myKey"].GetBytes();
                    },
```

It is probably a good idea to add this as an extension method to all event context's though as the above code is a bit chatty and not very straight forward to other people than myself :D 

Please let me know if this solved your issue and feel free to report any other issues you might have.

**Comment by KhaledSMQ** [comment]
Thank you @smatsson , That useful and i already manage to solve it using OnCreateCompleteAsync event.

Thank you for Tus project, it's just amazing and clean code.

**Comment by smatsson** [comment]
You are very welcome @KhaledSMQ ! Thanks for the kind words :) I'll look into making it easier to read metadata etc in events in an upcoming release.

**Comment by smatsson** [comment]
Just realized that if you follow the example in the readme you can also just grab the metadata directly from the file as such:

```
OnCreateCompleteAsync = async ctx =>
                    {
                        var file = await ((ITusReadableStore)ctx.Store).GetFileAsync(ctx.FileId, ctx.CancellationToken);
                        var metadata = await file.GetMetadataAsync(ctx.CancellationToken);
                        var myValue = metadata["myKey"].GetString(Encoding.UTF8);
                    },
```

Either way is fine. :)

**Comment by KhaledSMQ** [comment]
actually this is what i did
```
OnCreateCompleteAsync = ctx =>
                    {
                        if (!ctx.Metadata.ContainsKey("app")) return Task.CompletedTask;
                        try
                        {
                            ctx.Metadata.TryGetValue("app", out var contentTo);
                            var ContentBytes = contentTo.GetBytes();
                            var app = Encoding.UTF8.GetString(ContentBytes);
                      }.......

```

**Comment by KhaledSMQ** [comment]
but i am not sure so i will give a try for the one give.
I just wonder if I can create an extensions for the server i have a use case for the images to optimize. right now i am just do that right after the upload complete.
what do you think and what is your advice.

**Comment by smatsson** [comment]
As a first step I would probably just do the image optimization in the `OnFileComplete` event. Something similar to what is shown in the readme: https://github.com/tusdotnet/tusdotnet#configure (implement the `DoSomeProcessing` method).
