### ISSUE TITLE
Expiration flag

### ISSUE THREAD

**Issue by KhaledSMQ** [tusdotnet/tusdotnet#42]
Is it possible to remove expiration flag using the contract ITusExpirationStore.cs , It's good idea to upload temporary files and when the file been confirmed for any other operation file will be saved as permanent file. 

any idea how to implement such kind to situation.

**Comment by KhaledSMQ** [comment]
Or maybe in other word to set expiration flag on a file and mark the file as template file might deleted after (n) time.

**Comment by smatsson** [comment]
I'm not really sure on your use case but wouldn't setting the expiry date to some time in the future work? 

```
store.SetExpirationAsync("myFile", DateTimeOffset.MaxValue, CancellationToken.None);
```

**Comment by KhaledSMQ** [comment]
@smatsson Thank you for reply
to understand more about SetExpirationAsync option what is doing for case i want to upload file temporary then i decided this temporary file i want to change status to permanent file i will just override the original expiration date by setting the max `12/31/9999 11:59:59 PM +00:00.`

**Comment by smatsson** [comment]
Got you :) Does that solve your issue?

**Comment by KhaledSMQ** [comment]
exactly

**Comment by KhaledSMQ** [comment]
i tried to work around this and the file is not deleted
```
  OnCreateCompleteAsync = async ctx =>
                    {
  var expirationStore = (ITusExpirationStore)ctx.Store;
                                    await expirationStore.SetExpirationAsync(ctx.FileId, DateTimeOffset.Now.AddMinutes(2), CancellationToken.None);
                                 }

in console 
Ysa.Api.Startup:Information: Running cleanup job...
Ysa.Api.Startup:Information: Removed 0 expired files. Scheduled to run again in 60000 ms

```
i can see in the following link where you checking 2 conditions must be valid to able to delete the file
```
.Where(f => FileHasExpired(f) && FileIsIncomplete(f))

https://github.com/tusdotnet/tusdotnet/blob/da7f7ca0811672748615772ae4ee8132b0a12d59/Source/tusdotnet/Stores/TusDiskStore.cs#L298

```
the idea is to set and unset expiration for even completed files.
maybe something like this
```
.Where(f => FileHasExpired(f) && (FileIsIncomplete(f) || ForceDeletion(f))
```

**Comment by smatsson** [comment]
Hi @KhaledSMQ 

I get what you are saying but I'm not sure if this is compatible with the Tus protocol.

"The Server MAY remove *unfinished uploads* once they expire. In order to indicate this behavior to the Client, the Server MUST add expiration to the Tus-Extension header."
Source: https://tus.io/protocols/resumable-upload.html#expiration

How do you determine if a file is temporary or not? Would it be possible to just remove the temporary files using `ITusTerminationStore.DeleteFileAsync`?

**Comment by KhaledSMQ** [comment]
@smatsson do you agree to have extinctions for tusdotnet allow to extending functionality to use on top of Tus protocol. There is so many scenarios to make the protocol in heart of every application.

**Comment by smatsson** [comment]
Not if the extension breaks the protocol or breaks interoperability with other tus servers. What you want to add is very specific to your own application. Extending an application is not the same as extending a library that needs to be compliant with a protocol and existing systems.

You could implement the functionality you need in other ways without modifying tusdotnet, e.g. save each ID to a collection and remove the IDs that are no longer marked as temporary. 

I am not completely against the option to cleanup completed files after an expiration as long as:
* It's not on by default (this would break compatibility with the protocol)
* There are no breaking changes to the protocol nor to the interfaces in tusdotnet. E.g. this must be a setting on the store being used (in this case TusDiskStore)
* It is well tested (i.e. 100% test coverage).

If you provide me with a PR for the above I will add it to the repo.

**Comment by smatsson** [comment]
Closed due to inactivity.
