### ISSUE TITLE
UrlPath problem

### ISSUE THREAD

**Issue by j-hudecek** [tusdotnet/tusdotnet#44]
I have an app that can be accessed from two different URLs (www.example.com/app1 and www.example.com/app2). The UrlPath parameter requires including the path base. Do I have to configure 2 Tus instances? Could we have a UrlPattern instead so that all URLs that look like "/[^/]*/files/" would be handled by Tus.

**Comment by smatsson** [comment]
Not a bad idea at all. It would need to be backwards compatible with the current way of doing things. Maybe a regex or a callback function, something like `bool ShouldHandleRequest(String uri)`. Note that the regex also needs to handle requests to files such as `/files/asdfg`

If you provide med with a PR I would be happy to merge it. Just make sure that all tests work and add new tests for the new functionality.

**Comment by smatsson** [comment]
Another solution that is probably simpler to use than regex/callbacks is to update the URL parsing code to better support virtual paths in the URL (e.g. `/app/files`).


Code is located here: https://github.com/tusdotnet/tusdotnet/blob/master/Source/tusdotnet/Extensions/ContextAdapterExtensions.cs

**Comment by smatsson** [comment]
Btw you can solve this without changing the code. The configuration factory used can return different values for the path property depending on which of the sites are being accessed.

**Comment by smatsson** [comment]
The comment above was written while in transit. To clarify: The func that you provide to `UseTus` will be executed on each request and will be provided the request as the only parameter. You can then determine from that request what UrlPath to listen to.

Example:
```
app.UseTus(context =>
{
	string urlPath;
	if (context.Request.Path.StartsWithSegments(new PathString("/app1/files/")))
	{
		urlPath = "/app1/files";
	}
	else
	{
		urlPath = "/app2/files";
	}

	return new DefaultTusConfiguration
	{
		UrlPath = urlPath,
		....
	};
});
```

**Comment by j-hudecek** [comment]
Yes, you're right, thanks!
