### ISSUE TITLE
progress

### ISSUE THREAD

**Issue by anicething** [tusdotnet/tusdotnet#47]
how to response the progress to user?

**Comment by smatsson** [comment]
Are you talking about the upload progress? This is handled automatically by the client libs. Here is an example for the js client: https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_netcoreapp2.1_TestApp/wwwroot/index.html#L88

**Comment by anicething** [comment]
@smatsson thx a lot.
