### ISSUE TITLE
Can't set large maximum upload size

### ISSUE THREAD

**Issue by rhsumner** [tusdotnet/tusdotnet#50]
DefaultTusConfiguration.MaxAllowedUploadSizeInBytes should be long not int I think in order to allow for larger file sizes.

**Comment by smatsson** [comment]
Good catch. This is an old remnant since tusdotnet only ran on .NET Framework as IIS has a max request size of 2147483647 bytes (int.MaxValue). This should not be a breaking change so I'll file it as a bug and fix it in an upcoming release. Thanks for reporting!

**Comment by smatsson** [comment]
2.1.3 is published to nuget.org and should be out soon. Release notes: https://github.com/tusdotnet/tusdotnet/releases/tag/2.1.3
