### ISSUE TITLE
Client example

### ISSUE THREAD

**Issue by fredeil** [tusdotnet/tusdotnet#54]
Is there any plans on implementing a reference client application for dotnet? I see that there are no examples for the uploading between client/server.

Thanks.

**Comment by smatsson** [comment]
Hi! 

No, no plans on implementing a client. There are already clients available for a bunch of different languages/platsforms over at https://tus.io/implementations.html

What kind of examples are you after? The full spec is available on https://tus.io/protocols/resumable-upload.html or you could use one of the test sites in this repo and check Chrome's dev tools on how requests are made.
