### ISSUE TITLE
How custom return metadata in OnFileCompleteAsync

### ISSUE THREAD

**Issue by guiraamos** [tusdotnet/tusdotnet#64]
I need return a ID's object in OnFileCompleteAsync.

**Comment by smatsson** [comment]
Return the ID to the client or where do you need to return it to? The tus protocol does not contain any specification on returning data for a successful upload. Your best bet is probably to add a custom header with your ID.

Something like:
```
OnFileCompleteAsync = ctx => 
{
    var id = DoStuffAndGetId();
    ctx.HttpContext.Response.Headers.Add("MyId", id);
}
```
