### ISSUE TITLE
Matching the correct file with the correct client

### ISSUE THREAD

**Issue by Unthred** [tusdotnet/tusdotnet#66]
I must be miss-understanding something here.
Everything works fine if I have just one client at a time uploading, but when I have multiple clients they are getting the wrong file from the store. Am I being a complete dufus? 

What I would really like is to be able to extract the metadata in the OnFileCompleteAsync but I cant see any way of doing that.

So I create the upload like so
````  
  var file = new FileInfo(filename);
  var client = new TusClient();
  (string, string)[] metadata = {
    ("product", fileRetrievalInfo.DisplayName), 
    ("fileType", fileRetrievalInfo.RetrievalType.ToString()),
    ("id", surveyor.Id.ToString())
   };
    var fileUrl = await client.CreateAsync(uploadAddress, file.Length, metadata);
    var uploadOperation = client.UploadAsync(fileUrl, file, chunkSize);

and when I receive the file I have

_tusConfiguration.Store = new TusDiskStore(diskStore, true);
_tusConfiguration.UrlPath = "/webapi/v1/File/NewFileUpload";
_tusConfiguration.Expiration = new SlidingExpiration(expiration);
_tusConfiguration.Events = new Events
{
  OnBeforeCreateAsync = ctx =>
  {
    if (ctx.Metadata.TryGetValue("product", out var product))
      _product = Encoding.UTF8.GetString(product.GetBytes());
    else
       ctx.FailRequest("Product metadata must be specified. ");

    if (ctx.Metadata.TryGetValue("fileType", out var fileType))
      _fileType = Encoding.UTF8.GetString(fileType.GetBytes());
    else
       ctx.FailRequest("FileType metadata must be specified. ");

    if (ctx.Metadata.TryGetValue("id", out var surveyorId))
      _surveyorId = Guid.Parse(Encoding.UTF8.GetString(surveyorId.GetBytes()));
    else
      ctx.FailRequest("Id metadata must be specified. ");

    return Task.CompletedTask;
  },
  OnFileCompleteAsync = async ctx =>
  {
    // ctx.FileId is the id of the file that was uploaded.
    // ctx.Store is the data store that was used (in this case an instance of the TusDiskStore)
     var file = await ((ITusReadableStore) ctx.Store).GetFileAsync(ctx.FileId, ctx.CancellationToken);
     var result = await ProcessFile(ctx.CancellationToken, file);
     if (!result.Success)
     {
       throw new MyProcessingException("Something went wrong during processing");
     }
   },
````
Thanks

**Comment by smatsson** [comment]
Hi!

It seems very odd that `GetFileAsync` would return the wrong file for a file id as it's basically just picking the file with the same name as the id from disk. Are they getting the wrong file in the `OnFileCompleteAsync` callback?

To get the metadata in `OnFileCompleteAsync` you can call `GetMetadataAsync` on your `file` which will give you the same metadata object as `ctx.Metadata` in `OnBeforeCreateAsync`. 

On mobile so pardon the brevity.

**Comment by Unthred** [comment]
Oh its probably my fault as I am setting a class variable in OnBeforeCreateAsync and then using that in OnFileCompleteAsync to identify the file and some other client in coming in and setting it again.

What I really needed is to get the meta data in OnFileCompleteAsync which you have given me. This I suspect will solve my issues. 

Thanks very much for the prompt reply!

**Comment by smatsson** [comment]
Happy to help. Let me know if it solved your issue.

**Comment by Unthred** [comment]
I am pretty sure it now works fine.... wont be 100% sure until I can put it in production as my test rig is just not large enough. 

Thanks loads for your help
