### ISSUE TITLE
How to change data storage?

### ISSUE THREAD

**Issue by pnrBehnamm** [tusdotnet/tusdotnet#68]
Hi, I created an Asp.net Core 2 project I want to change data storage in Tusdotnet library how can do it?

for example, I want to store in a specific table of SQL server database, do you have the case of that?

**Comment by smatsson** [comment]
Hi!

The data storage is determined by what data store you are using. tusdotnet ships with a store that writes data to disk but it's quite easy to implement your own store for your SQL schema. 

See this wiki page for more info: https://github.com/tusdotnet/tusdotnet/wiki/Custom-data-store
