### ISSUE TITLE
can I join tusdotnet

### ISSUE THREAD

**Issue by bluetianx** [tusdotnet/tusdotnet#70]
I have a [DotNET client implementation of the Tus protocol](https://github.com/bluetianx/BirdMessenger) ，I want to join tusdotnet，

**Comment by smatsson** [comment]
Hi! 

Thanks for reaching out. I'm currently not interested in incorporating a client into tusdotnet with the main reason being that there are already a couple of clients for .NET out there (see https://tus.io/implementations.html).

You can probably get your client listed on https://tus.io/implementations.html by sending a PR for this file: https://github.com/tus/tus.io/blob/master/_pages/implementations.md

**Comment by bluetianx** [comment]
ok
