### ISSUE TITLE
Expose interface for custom ID provider or make CreateFileAsync of TusDiskStore virtual

### ISSUE THREAD

**Issue by philippk80** [tusdotnet/tusdotnet#71]
I think the title says it all.
This is useful if custom ID's are needed.

I need for example Guid.NewGuid().ToString("D");

**Comment by smatsson** [comment]
The title definitely does not say it all. Why do you need that particular format?

**Comment by philippk80** [comment]
Because in SQL-Server Guid are saved in a uniqueidentifier column and excepts the "D"-Format.
It would be useful to use the idenitifer as id in a table without having an extra path column with some other random identifer. 
ItemTable:
- ID: uniqueidentifier
- Path: varchar               
So Path is ID.extension for example
It's just to have a clean ecosystem. 
It's not a requirement to use it.

**Comment by smatsson** [comment]
It seems that you could very easily work around this by doing `var myDbId = Guid.ParseExact(myFileId, "n")` (or possibly `var myDbId = Guid.ParseExact(myFileId, "n").ToString("d")`) and then pass `myDbId` to EF/Dapper/whatever? 

I like the idea of having a file id generator but I think that the idea needs to be refined more before being implemented. Properly done it would be a great aid and allow developers to create file uploads linked to already existing ids such as db rows, documents in MongoDb or some entry in CRM/SAP/whatever system that isn't easily modified.

I'm thinking that the interface for this must be passed to the TusDiskStore (as it is responsible for creating ids) and must support both creating and validating that an ID is correct. The default implementation probably still needs to be the current one to now cause breaking changes. The id generator would also need to be 100% responsible for not creating duplicate ids as there is no way for TusDiskStore (nor tusdotnet in general) to know if the ids are unique.

Feel free to submit a PR for this change.

**Comment by smatsson** [comment]
@philippk80 Any progress on that PR?

**Comment by philippk80** [comment]
It's just an untested draft but I started a PR so the progress is visible.
I don't think I have the time to work on it the next weeks.

**Comment by smatsson** [comment]
@philippk80 Awesome! :) Take your time, it's no hurries. Just wanted to check in.

**Comment by philippk80** [comment]
But basically it should already work... the change isn't thaaat big.

**Comment by philippk80** [comment]
Maybe the creation of the id should be moved to a new interface-method so the implementation is forced to do so. Otherwise it isn't guaranteed that the id is a new generated one. With the current implementation every third party class is able to control that over the constructor.

**Comment by smatsson** [comment]
Agreed. It's probably a cleaner approach having something like
```
  public interface ITusFileIdProvider
  {
      Task<string> Create();
      Task<string> Verify(string fileId); // returns the input, basically just for chaining. Return type could probably also be just Task
  }
```

I'm not a fan of how TusDiskStore uses a generic constraint for the ITusFileIdProvider and would rather see a solution similar to how TusDiskBufferSize works where we can provide one in the constructor, or a default one is used. The reason for this is that we would then allow a custom file id provider to take in additional constructor params, such as db connections or whatever. Just example code thrown together now:
```
public class ExistingDbFileIdProvider : ITusFileIdProvider
{
    private IDbContext _context;

    public ExistingDbFileIdProvider(IDbContext context)
    {
        _context = context;
    }

    public async Task<string> Create() 
    {
        return await _context.SomeTable.GetLatestAvailableId();
    }

    public async Task<string> Verify(string fileId)
    {
        // Do something...
        return fileId;
    }
}
```

Another idea would be to pass the provided metadata into the `Create` method which would allow us to let the client decide on the ID, or use something provided by the client as base for the ID.

Great work so far! Thanks for your effort :)

**Comment by philippk80** [comment]
I've done that for simplicity. Another option would be a parameter in the TusDiskStore that describes a Factory for the id. (Action<ITusFileIdProvider>) Then everything would be possible.

**Comment by smatsson** [comment]
I've been thinking about the interface for ITusFileProvider and we should probably not keep instance properties (i.e. FileId) in it just to make it possible to keep a singleton value in the IoC container (if needed for some reason, e.g. DB connections).
