### ISSUE TITLE
Dynamically choosing store location via Metadata parameter

### ISSUE THREAD

**Issue by verystack** [tusdotnet/tusdotnet#77]
If I wanted to update the Store location in DefaultTusConfiguration based on metadata, is this currently possible? 

Right now I'm creating a second folder location and new Store within OnFileCompleteAsync and then transferring the file to that store and deleting the existing one. I have thought about doing 

```
var path = httpContext.Request.Path.Value.Split("/").Skip(2).FirstOrDefault();                
TusDiskStore store;
store = new TusDiskStore($@"C:\tusfiles\{path}");
```
 and validating this before returning DefaultTusConfiguration, but would rather not integrate an identifier into a URL.

Surely there is an easier way to do this?

**Comment by smatsson** [comment]
Hi!
It depends on what you define as "metadata". The configuration factory (the lambda provided to `app.UseTus` ) is executed on every request and the current http context is provided to it. If the metadata to use is provided in each reuqest, or if you can determine the metadata from something in the request such as the username or similar, then you can simply return the correct store location up front. The problem with using the `Upload-Metadata` provided by the client when creating the file is that that metadata is stored together with the file in the store's location so there is no easy way to find the file (and the metadata) without knowing the store's location. Maybe you could store the file id and the metadata needed in a common location (he it on disk or in a DB) used for all files and then use that to return the correct configuration from the configuration factory? Would that solve your issue? It would be faster than moving the entire file once completed.

On mobile so pardon the brevity. Please let me know if anything is unclear.
