### ISSUE TITLE
file download and file url error

### ISSUE THREAD

**Issue by anu035** [tusdotnet/tusdotnet#82]
I have uploaded one file ,there was four file created

![tuserror](https://user-images.githubusercontent.com/10250123/73841366-7407da80-4840-11ea-9156-f49513a348f1.png)
but i can not able to see original file and once i cclick on download it saying no such file is there
my code is

using Microsoft.Owin;
using Microsoft.Owin.Cors;
using Owin;
using System;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using tusdotnet;
using tusdotnet.Interfaces;
using tusdotnet.Models;
using tusdotnet.Models.Configuration;
using tusdotnet.Stores;

[assembly: OwinStartupAttribute(typeof(fileupload.Startup))]
namespace fileupload
{
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            //ConfigureAuth(app);
            var corsPolicy = new System.Web.Cors.CorsPolicy
            {
                AllowAnyHeader = true,
                AllowAnyMethod = true,
                AllowAnyOrigin = true
            };

            // ExposedHeaders has a private setter for some reason so one must use reflection to set it.
            corsPolicy.GetType()
                .GetProperty(nameof(corsPolicy.ExposedHeaders))
                .SetValue(corsPolicy, tusdotnet.Helpers.CorsHelper.GetExposedHeaders());

            app.UseCors(new CorsOptions
            {
                PolicyProvider = new CorsPolicyProvider
                {
                    PolicyResolver = context => Task.FromResult(corsPolicy)
                }
            });

            app.UseTus(httpContext => new DefaultTusConfiguration
            {
                Store = new TusDiskStore(@"E:\fileupload\"),
                UrlPath = "/files",
                Events = new Events
                {
                    OnAuthorizeAsync = eventContext =>
                    {
                        //if (!eventContext.HttpContext.User.Identity.IsAuthenticated)
                        //{
                        //    eventContext.FailRequest(HttpStatusCode.Unauthorized);
                        //    return Task.FromResult(0);
                        //}

                        //// Do other verification on the user; claims, roles, etc. In this case, check the username.
                        //if (eventContext.HttpContext.User.Identity.Name != "test")
                        //{
                        //    eventContext.FailRequest(HttpStatusCode.Forbidden, "'test' is the only allowed user");
                        //    return Task.FromResult(0);
                        //}

                        // Verify different things depending on the intent of the request.
                        // E.g.:
                        //   Does the file about to be written belong to this user?
                        //   Is the current user allowed to create new files or have they reached their quota?
                        //   etc etc
                        switch (eventContext.Intent)
                        {
                            case IntentType.CreateFile:
                                break;
                            case IntentType.ConcatenateFiles:
                                break;
                            case IntentType.WriteFile:
                                break;
                            case IntentType.DeleteFile:
                                break;
                            case IntentType.GetFileInfo:
                                break;
                            case IntentType.GetOptions:
                                break;
                            default:
                                break;
                        }

                        return Task.FromResult(0);
                    },
                    OnBeforeCreateAsync = ctx =>
                    {
                        if (!ctx.Metadata.ContainsKey("filename"))
                        {
                            ctx.FailRequest("name metadata must be specified. ");
                        }

                        if (!ctx.Metadata.ContainsKey("filetype"))
                        {
                            ctx.FailRequest("contentType metadata must be specified. ");
                        }

                        return Task.FromResult(0);
                    },
                    OnBeforeDeleteAsync = ctx =>
                    {
                        if (1 != 0)
                        {
                            ctx.FailRequest($"Cannot delete {ctx.FileId} due to business logic");
                        }

                        return Task.FromResult(0);
                    },
                    OnDeleteCompleteAsync = ctx =>
                    {
                        //logger.LogInformation($"Deleted file {ctx.FileId} using {ctx.Store.GetType().FullName}");
                        return Task.FromResult(0);
                    },

                    OnFileCompleteAsync = async eventContext =>
                    {
                        // eventContext.FileId is the id of the file that was uploaded.
                        // eventContext.Store is the data store that was used (in this case an instance of the TusDiskStore)

                        // A normal use case here would be to read the file and do some processing on it.
                        ITusFile file = await eventContext.GetFileAsync();
                        //var result = await     DoSomeProcessing(file, eventContext.CancellationToken);

                        //if (!result.Success)
                        //{
                        //    throw new MyProcessingException("Something went wrong during processing");
                        //}
                    }
                }
            });
            app.Use(async (context, next) =>
            {
                // /files/ is where we store files
                if (context.Request.Uri.LocalPath.StartsWith("/files/", StringComparison.Ordinal))
                {
                    // Try to get a file id e.g. /files/<fileId>
                    var fileId = context.Request.Uri.LocalPath.Replace("/files/", "").Trim();
                    if (!string.IsNullOrEmpty(fileId))
                    {
                        var store = new TusDiskStore(@"E:\fileupload\");
                        var file = await store.GetFileAsync(fileId, context.Request.CallCancelled);

                        if (file == null)
                        {
                            context.Response.StatusCode = 404;
                            await context.Response.WriteAsync($"File with id {fileId} was not found.", context.Request.CallCancelled);
                            return;
                        }

                        var fileStream = await file.GetContentAsync(context.Request.CallCancelled);
                        var metadata = await file.GetMetadataAsync(context.Request.CallCancelled);

                        // The tus protocol does not specify any required metadata.
                        // "contentType" is metadata that is specific to this domain and is not required.
                        context.Response.ContentType = metadata.ContainsKey("contentType")
                         ? metadata["contentType"].GetString(Encoding.UTF8)
                         : "application/octet-stream";

                        if (metadata.ContainsKey("name"))
                        {
                            var name = metadata["name"].GetString(Encoding.UTF8);
                            context.Response.Headers.Add("Content-Disposition", new[] { $"attachment; filename=\"{name}\"" });
                        }

                        await fileStream.CopyToAsync(context.Response.Body, 81920, context.Request.CallCancelled);
                        return;
                    }
                }

            });

        }
    }
}

**Comment by smatsson** [comment]
Hi,

tusdotnet will save four (or more) files for each upload. The data file (the one containing the actual file's data) is the one without a file extension.

Downloads are not handled by tusdotnet at all and you need to write custom code for it. I'm guessing that the code you posted is copied from the OWIN test site in the repo? It seems to be OK. What URL are you accessing to download the file? You should be able to debug the download code by setting a breakpoint on the line that starts with `if (context.Request.Uri.LocalPath.StartsWith("/files/"...`

**Comment by anu035** [comment]
thanks for your reply,can you tell me how to get file with exstension,like if i upload .mp4 then i will get .mp4 etc.

**Comment by smatsson** [comment]
The client needs to provide the file name or the extension as metadata and then read the metadata from the file. This is done in the test sites in this repo.

Client providing metadata: https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_netcoreapp3.1_TestApp/wwwroot/index.html#L90

Backend reading the metadata:
https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_netcoreapp3.1_TestApp/Endpoints/DownloadFileEndpoint.cs#L33

**Comment by anu035** [comment]
thank you for reply,see i did that and i have recived file like
http://demo5.ida.org.in/files/d83ba37e729a462a9c2239bb5a53cb50 this is an video file.
problem is we can forword or backword this video file in anyplayr it just playing 
foer example 

<!DOCTYPE html> 
<html> 
<body> 

<video width="400" controls>
  <source src="http://demo5.ida.org.in/files/d83ba37e729a462a9c2239bb5a53cb50" type="video/mp4">
  
  Your browser does not support HTML5 video.
</video>

<p>
Video courtesy of 
<a href="https://www.bigbuckbunny.org/" target="_blank">Big Buck Bunny</a>.
</p>

</body> 
</html>

check this code

**Comment by anu035** [comment]
we can not move forword and backword for video file

**Comment by smatsson** [comment]
You are not providing the browser with any of the headers required to be able to seek the video file.
![image](https://user-images.githubusercontent.com/4600361/73942757-e5eb2d00-48ef-11ea-92ba-55787b44b969.png)

You need to read up the `Accept-Range` and `Range` headers:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Ranges
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range

**Comment by anu035** [comment]
THANKS FOR YOUR REPLY,see we are using some custome player like jw playar for playing this video
so there is one option only to privide video source link,how can i give this range there.can we do something while uploading video only.

**Comment by anu035** [comment]
and in jw player or other player the video can not played this error comes.

**Comment by anu035** [comment]
once i use https://tus.io/demo.html this link and once clikc on download this download the file with extension which is required but once i used your given code this open video in browser not downloading original file with extension,can you share me this link download code this is working properily.,

**Comment by smatsson** [comment]
This has nothing to do with tusdotnet at all. The tus protocol is just for uploading files, not streaming video downloads. Your server needs to provide the `Accept-Range` header so that the browser can supply the `Range` header. This is described in the links I posted.
