### ISSUE TITLE
SourceLink Path Bug

### ISSUE THREAD

**Issue by marlon-tucker** [tusdotnet/tusdotnet#84]
Hello,

Using version `2.2.2` 

I'm trying to debug why a PATCH request isn't being handled by the tusdotnet middleware and have discovered an issue with the source link to the github project. 

Visual studio is attempting to load the source from this url:

`https://raw.githubusercontent.com/tusdotnet/tusdotnet/e139c0f4d4e53b8728065bd618a5b7f54e85d990/Tools/tusdotnet/ExternalMiddleware/Core/TusCoreMiddleware.cs`

However this returns 404 not found. The correct url would be:

`https://raw.githubusercontent.com/tusdotnet/tusdotnet/e139c0f4d4e53b8728065bd618a5b7f54e85d990/Source/tusdotnet/ExternalMiddleware/Core/TusCoreMiddleware.cs`

I notice the tools folder contains the ps1 script which builds the nuget package. It seems that is interfering with the path somehow. 

I'm not hugely familiar with how the source linking process works as I haven't personally published a nuget package so I'm not sure if this is a bug in this repo or a bug in the source link project.

Thanks

Marlon

**Comment by smatsson** [comment]
Interesting, thanks for reporting. Will have a look and fix it for the 2.3 release. Probably an issue with the build script.

**Comment by smatsson** [comment]
I have updated the symbol package on nuget but it will apparently take some time before it has been indexed:

``` 
The symbols for this package have not been indexed yet. They are not available for download from the NuGet.org symbol server. Symbols will be available for download after both validation and indexing are complete. Symbols validation and indexing may take up to an hour. Read more.
```

Once completed, you should be able to grab the new symbol package by deleting your local cache copy then restore nuget packages. Local cache is found in:
```
Windows: %userprofile%\.nuget\packages
Mac/Linux: ~/.nuget/packages
```

**Comment by marlon-tucker** [comment]
Thank you, in the mean time I got around it by cloning the repo, going to the 2.2.2 tag and pointing VS at that source.

**Comment by smatsson** [comment]
Apparently nuget.org cannot validate the new symbol package and only gives me a vague error. I have contacted nuget support to see if they can help me out.
