### ISSUE TITLE
There is a exception when I upload a big file

### ISSUE THREAD

**Issue by bluetianx** [tusdotnet/tusdotnet#86]
It is a exception I find by log，was it resolve  in the new release？
tusdotnet version ：2.1.2
asp net core ：2.1
 app run： windows server ，IIS

`A task was canceled.||stacktrace：   at tusdotnet.ProtocolHandlers.PatchHandler.<>c__DisplayClass9_0.<<GetOrUpdateExpires>g__UpdateExpiredLocal|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at tusdotnet.ProtocolHandlers.PatchHandler.Handle(ContextAdapter context)
   at tusdotnet.TusProtocolHandler.InvokeAsync(ContextAdapter context, ProtocolMethodHandler methodHandler)
   at tusdotnet.TusCoreMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
`

**Comment by mianbilal30** [comment]
Maybe this is helpful for you 
https://github.com/tusdotnet/tusdotnet/wiki/Configure-IIS

or 

try this in startup class in configure method`
`app.Use((context, next) =>
            {
                context.Features.Get<IHttpMaxRequestBodySizeFeature>().MaxRequestBodySize = null;
                return next.Invoke();
            });`

**Comment by bluetianx** [comment]
first ：  I did it by follow code 
second : It is not a always error,  It comes up occasionally when there are very much task of upload file.
I think that Because the disk pressure read and write pressure is too high，But I don't know how to prove my idea ,So I  ask you if you have the same problem

`.UseKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = null;
                    options.Limits.MaxRequestBufferSize = null;
                })`

**Comment by smatsson** [comment]
Hi,

I haven't seen this issue before but would say that it is either due to execution timeouts on the server or the client disconnecting in some unfortunate place. 

I'll leave this one open, please let me know if you gather any more details on when or how this happens.

**Comment by bluetianx** [comment]
ok， I will try resolve this problem by upgrade tusdotnet to 2.2.2

**Comment by smatsson** [comment]
Yeah I think that is the best bet. `PatchHandler` isn't used anymore and has been replaced with `WriteFileHandler`. My best guess is that this has to do with timing when the client disconnects. It might have been fixed automatically in a later version as the entire handling of file writes was rewritten. If not, please let me know and I'll investigate.

**Comment by smatsson** [comment]
@bluetianx Was this resolved by updating to a later version?

**Comment by bluetianx** [comment]
yep，This has been resloved。The problem seems to be a result of server stress。I scaled out and upgraded tusdotnet 。

**Comment by smatsson** [comment]
Glad to hear it!
