### ISSUE TITLE
I can't find the property MetadataParsingStrategy in DefaultTusConfiguration in v2.2.2

### ISSUE THREAD

**Issue by veteran1** [tusdotnet/tusdotnet#88]
Hello 
Looks like the MetadataParsingStrategy property is missing, can you please update the package? or how can I use it in v2.2.2

**Comment by smatsson** [comment]
Hi,

It's been on my to-do list for some time now. I'll see if I can get it released today or some time this week.

**Comment by veteran1** [comment]
Thank you for your reply,
I'm planning on using tusdotnet with .net core webapi, but i can't upload please take a look at the image bellow,

![fileupload](https://user-images.githubusercontent.com/993610/77528594-842a5680-6e8e-11ea-99d9-91972965786a.PNG)

Im using [tus js client](https://github.com/tus/tus-js-client) in my angular app.
Is it possible to use tusdotnet with webapi?
Best regards

**Comment by dmytrohridin** [comment]
Hello @smatsson 
I have the same issue with version 2.2.2
but when I switch my client to ASP.NET Core 3.1 example which contains MetadataParsingStrategy - everything works. How it can be done without a parsing strategy? Thank you

**Comment by dmytrohridin** [comment]
Seems I found solution
@veteran1 in client js app just remove "emptyMetaKey"
So your metadata should look like
`metadata: {
                        name: file.name,
                        contentType: file.type || 'application/octet-stream'
                    }`

**Comment by veteran1** [comment]
Hi, unfortunatly didn't work for me,

I dig a little bit in code, and changed [this line](https://github.com/tusdotnet/tusdotnet/blob/414449991b1ed008dbb3fa7d1d1afcbb38f7763d/Source/tusdotnet/TusProtocolHandlerIntentBased.cs#L70) with `return ResultType.StopExecution`. now i can upload metadata but not the file 
![metadata](https://user-images.githubusercontent.com/993610/77542207-1db13280-6ea6-11ea-85e5-3d6cf51600ee.PNG)

in the other hand, the variable [hasData](https://github.com/tusdotnet/tusdotnet/blob/414449991b1ed008dbb3fa7d1d1afcbb38f7763d/Source/tusdotnet/Adapters/WriteFileContextForCreationWithUpload.cs#L31) seems to be equal to false all the time, even tho im sur i send the body data with postman.
any help would be appreciated.
Thanks

**Comment by smatsson** [comment]
> Hi, unfortunatly didn't work for me,
> 
> I dig a little bit in code, and changed [this line](https://github.com/tusdotnet/tusdotnet/blob/414449991b1ed008dbb3fa7d1d1afcbb38f7763d/Source/tusdotnet/TusProtocolHandlerIntentBased.cs#L70) with `return ResultType.ContinueExecution`. now i can upload metadata but not the file
> ![metadata](https://user-images.githubusercontent.com/993610/77542207-1db13280-6ea6-11ea-85e5-3d6cf51600ee.PNG)

Changing a random line without understanding the code is rarely a good idea. What error message did you get (before changing the code)? 

> in the other hand, the variable [hasData](https://github.com/tusdotnet/tusdotnet/blob/414449991b1ed008dbb3fa7d1d1afcbb38f7763d/Source/tusdotnet/Adapters/WriteFileContextForCreationWithUpload.cs#L31) seems to be equal to false all the time, even tho im sur i send the body data with my angular client app.
> any help would be appreciated.
> Thanks

`hasData` is only true if the upload-with-creation extension is used, which is not enabled by default in tus-js-client.

**Comment by veteran1** [comment]
Before changin the code, i get this error in chrome console:
Access to XMLHttpRequest at 'https://localhost:5001/fileupload' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
in my startup i have this configuration:

`app.UseCors(builder => builder.AllowAnyOrigin()
                                           .AllowAnyMethod()
                                           .AllowAnyHeader());`

**Comment by smatsson** [comment]
That error is due to your CORS policy being wrong. Removing `return ResultType.StopExecution` "works" because you told the ASP.NET Core runtime to continue running the code even though tusdotnet has finished with the request. This is probably why the next request (the one that writes data) fails.

See here how to setup CORS: https://github.com/tusdotnet/tusdotnet/wiki/Cross-domain-requests-(CORS)#aspnet-core (note the order of the `app.Use...` calls. The order matters).

**Comment by veteran1** [comment]
@smatsson it did work, thank you very muh :)

**Comment by smatsson** [comment]
2.3 is out: https://www.nuget.org/packages/tusdotnet/2.3.0
