### ISSUE TITLE
404 Error on PATCH requests using a custom chunk size

### ISSUE THREAD

**Issue by leo2d** [tusdotnet/tusdotnet#91]
I am implementing tusdotnet in my .Net core 2.2 API and it works well locally. But when I deployed to the server, I received a 404 error when setting the "chunk size" on the client. If I don’t set the "chunk size", it sometimes works, sometimes it give me the same error when finishing the upload.

Inspecting the request, I saw that this error is occurring in the second PATCH request:

![image](https://user-images.githubusercontent.com/28194654/83921047-f0a9b780-a753-11ea-80ef-d6e8daecd886.png)

In the example above, I tried to upload a 115 MB file with a limited "chunk size" of 1 MB on the client.

More information:

tusdotnet : 2.3.0
dotnet core: 2.2
production server: IIS
locally: Kestrel and IIS Express(works on both)

My Tus config on Startup is the same as the [AspNetCore_netcoreapp2.2_TestApp](https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_netcoreapp2.2_TestApp/Startup.cs)

My IWebHostBuilder creation on Program.cs:

```csharp

public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
            WebHost.CreateDefaultBuilder(args)
                .UseApplicationInsights()
                .UseUrls("http://0.0.0.0:3009")
                .UseSerilog()
                .UseStartup<Startup>()
                .ConfigureKestrel(options =>
                {
                    options.Limits.MaxRequestBodySize = null;
                    options.Limits.MaxRequestBufferSize = null;
                });


```

My web.cofig:

<?xml version="1.0" encoding="utf-8"?>
```xml

<configuration>
    <location path="." inheritInChildApplications="false">
        <system.webServer>
            <modules>
                <remove name="WebDAVModule" />
            </modules>

            <handlers>
                <remove name="aspNetCore" />
                <remove name="WebDAV" />
                <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
            </handlers>
            <aspNetCore requestTimeout="00:20:00" processPath="%LAUNCHER_PATH%" stdoutLogEnabled="false"
                        stdoutLogFile=".\logs\stdout" hostingModel="InProcess" arguments="%LAUNCHER_ARGS%">
                <environmentVariables>
                    <environmentVariable name="COMPLUS_ForceENC" value="1" />
                    <environmentVariable name="ASPNETCORE_ENVIRONMENT" value="Development" />
                </environmentVariables>
            </aspNetCore>
            <security>
                <requestFiltering>
                    <!-- This will handle requests up to 1000MB -->
                    <requestLimits maxAllowedContentLength="1000000000" />
                </requestFiltering>
            </security>
        </system.webServer>
    </location>
</configuration>
```

**Comment by smatsson** [comment]
Hi!

Thanks for reporting and kudos on providing all the information needed to be able to trouble shoot.

As it works on your localhost and not over the internet I would guess that it has something to do with the infrastructure or latency on the internet. When using chunks you will be using multiple smaller HTTP requests which could end up on different servers in a load balanced environment. What response are you getting if you perform a HEAD request for the failed file?

``` 
Invoke-WebRequest -Uri "https://localhost:5003/files/cfed3fd944e347f29edb7b2c9578f9cb" `
-Method "HEAD" `
-Headers @{
"Pragma"="no-cache"
  "Tus-Resumable"="1.0.0"
}
``` 

Another thing worth looking into is changing the expiration property to some larger value and/or using sliding expiration. I could get the same thing to happen on localhost with an absolute expiration of 5 sec:
![image](https://user-images.githubusercontent.com/4600361/84006229-aa7c7000-a96e-11ea-8d67-831655fdd06d.png)

**Comment by leo2d** [comment]
@smatsson Thank you for the support.

I was using an AbsoluteExpiration of 5 minutes, then I change to 1 hour, but the behavior still the same.

I tried to do a Head request to the same URL used in a failed PATCH and it returns me "OK" with the right information:

![image](https://user-images.githubusercontent.com/28194654/84030393-5e2f3100-a96a-11ea-997f-22b649aa46ea.png)

I checked with the infra people about load balancers and they told me we have 2 instances for this app, but the second one just  "wakes up" when the first one cannot accept more requests.

**Comment by smatsson** [comment]
Hmm weird. Some things that come to mind:

- If you re-send the HEAD request 10-15 times, are you still getting the same response?
- What's the response headers and body of the 404 PATCH? 
- After the 404 PATCH, is the file actually update on the server, or does the 404 happen before?

**Comment by leo2d** [comment]
@smatsson I conclude that it was really a problem with infra and, due to the load balancer, keep chunks on the server could not be a good idea. So I decided to implement my own chunk upload solution to Azure Blob Storage, instead of store chunks on the server. So I'm closing this issue now. 
Thanks for your support!

**Comment by smatsson** [comment]
No problem. 😊 Let me know if you decide to open source your store and I'll add a link in the readme.
