### ISSUE TITLE
Swagger/Swashbuckle support

### ISSUE THREAD

**Issue by 1100594** [tusdotnet/tusdotnet#95]
Hi,

Does tusdotnet nuget supports swagger/ Swashbuckle specification?

Best regards,

**Comment by smatsson** [comment]
Hi, 

No there is no support for Swagger in tusdotnet. I don't think I have seen any definitions for Swagger for the tus protocol at all. You might try asking over at the protocol's repo: https://github.com/tus/tus-resumable-upload-protocol/issues

What do you need it for? :) Clients are listed on https://tus.io/implementations.html and you can use any of the [test sites ](https://github.com/tusdotnet/tusdotnet/tree/master/Source/TestSites/AspNetCore_netcoreapp3.1_TestApp)together with Chrome dev tools to see what is going on.

**Comment by 1100594** [comment]
Hi @smatsson,

It was only for documentation and api spec validation. 
I also haven't seen any TUS's definitions for Swagger.
Thanks for the suggestions, we are already using one's of the listed clients.

Thanks for the reply.

**Comment by smatsson** [comment]
The protocol now contains an OpenApi specification: https://github.com/tus/tus-resumable-upload-protocol/tree/master/OpenAPI

**Comment by 1100594** [comment]
Hi @smatsson,
Thanks for the information!
