### ISSUE TITLE
Where and What to return to tell the client its request was ok but not processed and he should try again later (throttling, limits)

### ISSUE THREAD

**Issue by michaelrall** [tusdotnet/tusdotnet#96]
Hello,

I'm trying to limit the number of active uploads based on my internal account-id. So it's not the bandwidth I want to limit, but the number of concurrent uploads for one account (uploads might come from different PC's, so a restriction on the TUS-client would not help).

Where would be the point to tell a client, that I received his request and it was ok but I didn't process it. So the client should wait a sec until he sends his request again. Is there something within the TUS-Protocol to do this (like wait, or stalled, or whatever).

What can I return from the handling-routines instead of "Task.CompletedTask" to singal the client there was no error, but we didn't process his request either and he should retry?

cheers

**Comment by smatsson** [comment]
Hi,

Use the [`OnAuthorize` callback](https://github.com/tusdotnet/tusdotnet/wiki/OnAuthorizeAsync-event) to send any status code that you wish to the client (e.g. 429 Too Many Requests). The client would then get an error and could retry later. `OnAuthorize` is called on every request.

Some clients, e.g. [tus-js-client](https://github.com/tus/tus-js-client/blob/master/docs/usage.md#example-simple-file-upload), has automatic retries but there is nothing in the protocol that adds this feature.

Example:
```
app.UseTus(httpContext =>  new DefaultTusConfiguration
{
    ...
    Events = new Events
    {
        OnAuthorizeAsync = async eventContext =>
        {
            bool isThrottled = await CheckDatabaseOrWhateverForThrottledState(eventContext.HttpContext.User.Identity);

            if(isThrottled)
            {
                eventContext.FailRequest(HttpStatusCode.TooManyRequests, "Sorry but you have too many active uploads. Please try again later");
            }
        }
    }
});
```

Note that you could also use the `Intent` property from the `eventContext` to allow some requests, e.g. checking options or getting file info and just disallow the upload.

**Comment by michaelrall** [comment]
Hi,

thanks for your detailed answer. I'll give it a try.

cheers
