### ISSUE TITLE
Upload location server different than creation server

### ISSUE THREAD

**Issue by SnGmng** [tusdotnet/tusdotnet#97]
Can the server for upload creation be different one than the upload creation server?
I want to use this to implement geo replication and save the file at the nearest possible server.

For example the clien makes a request to
```http
POST /upload HTTP/1.1
Host: tus.example.org
Tus-Resumable: 1.0.0
```
Then the server calculates the nearest server to upload to.
for example:

- if the user is located in the west of USA it returns `us-west-1.example.org` server 
- if the user is in EU it returns `eu-1.example.org` server

and responds with the nearest server in the location header:
```http
HTTP/1.1 201 Created
Location: https://us-west-1.example.org/upload/24e533e02ec3bc40c387f1a0e460e216
Tus-Resumable: 1.0.0
```

Is this supported by the tus protocol? Would it interfere with `creation-with-upload` extension, since the creation servers can be different to the upload servers? How can i implement this using tusdotnet (on both the creation sever and the upload location server)?

I was thinking of just using a reverse proxy load balancer instead of dedicated dns records, but thats too expensive and would defy the purpose of having geo-replicated servers.

**Comment by smatsson** [comment]
Hi,

It's certainly doable but to be honest this is more of an infrastructure issue than an app issue and I would use a DNS load balancers (e.g. [Azure Traffic Manager](https://docs.microsoft.com/en-us/azure/traffic-manager/traffic-manager-overview)) to just return the correct IP to the client upfront.
