### ISSUE TITLE
TestSites only uses the name: contentType, which is not compatible with uppy. 

### ISSUE THREAD

**Issue by reece00** [tusdotnet/tusdotnet#99]
uppy
Upload-Metadata: relativePath bnVsbA==,name Q2hyeXNhbnRoZW11bS5qcGc=,type aW1hZ2UvanBlZw==,filetype aW1hZ2UvanBlZw==,filename Q2hyeXNhbnRoZW11bS5qcGc=
error
contentType metadata must be specified. 

TestSites
Upload-Metadata: name Q2hyeXNhbnRoZW11bS5qcGc=,contentType aW1hZ2UvanBlZw==,emptyMetaKey

**Comment by smatsson** [comment]
I have no idea what you are asking here? The test sites are not supposed to be hard coded for Uppy but to show case how to validate whatever metadata that the server and client agrees upon. The tus protocol does not enforce any metadata and just leaves it to the server and client to decide. 

If you look at the Startup class in each of the test sites you will see that it's just custom code that the developer can provide: https://github.com/tusdotnet/tusdotnet/blob/master/Source/TestSites/AspNetCore_netcoreapp3.1_TestApp/Startup.cs#L153
